### ISSUE TITLE
Fallback to http polling instead of WebSockets for browser support

### ISSUE THREAD

**Issue by trigun539** [cdr/code-server#1024]
Unable to use code-server with browsers that do not support WebSockets. This would be great if could be implemented since it'll help users that are unable to use a WebSocket compatible browser.

Using Edge and get following error (blank page):

![image](https://user-images.githubusercontent.com/508205/65510419-e6d07480-dea2-11e9-83e9-32aae8d8754b.png)
Thanks.

**Comment by sr229** [comment]
This is something we cannot support, unfortunately. We want to reduce the amount of patches we do at  VSCode (right now we reduced a lot of patches in VSCode we do by a factor of 10 by reusing VSCode Web), and there's no way to support Real-time communication other than RTC in VSCode. This will requires a major codebase refactor. So I'm closing this since it's not worth the engineering effort for such a minor use case.

**Comment by sr229** [comment]
As for Edge users, *please* use the Edge Insiders Beta.

**Comment by frank-dspeed** [comment]
@sr229 this is not enought info maybe you should discribe what you exactly mean like build this repo with the edge insider beta src code?

**Comment by sr229** [comment]
@frank-dspeed you're not making sense. What I said is do not use stable Edge, you can try Edge Insiders Beta which is Chromium-based for `code-server`.
