### ISSUE TITLE
Error in pytest, TypeError: Cannot read property '$' of undefined

### ISSUE THREAD

**Issue by fmder** [cdr/code-server#1025]
- `code-server` version: v10.15.1
- OS Version: Ubuntu 16.0.4
- Extension:  Python/Pytest

## Description

When I run tests on a sample project with only one test (that passes) 

## Steps to Reproduce
 
1. Start new project.
2. Add file test/test_this.py with content:
```python
import unittest
class TestThat(unittest.TestCase):
    def test_that_passes(self):
        pass
```
3. Install pytest in your python environment.
4. Select pytest as test framework in property ``python.testing.pytestEnabled``.
5. Run all tests.

The following error appears in th lower right corner and in the test log

![image](https://user-images.githubusercontent.com/961474/65512690-b2ab8280-dea7-11e9-828f-91ea294711c4.png)

**Comment by sr229** [comment]
We don't have a tag named `10.15.1` so can you try using the latest preview to see if that works?

**Comment by fmder** [comment]
Ok, it looks like code-server --version return the wrong version then.

![image](https://user-images.githubusercontent.com/961474/65524372-b0ebba00-debb-11e9-8e45-e32ba8ac6a21.png)

**Comment by code-asher** [comment]
That's very interesting; it looks like code-server is passing the 
`--version` flag straight to Node since that's the version of Node 
bundled with code-server. I've seen it before in an improper 
build. How was this binary obtained?

**Comment by code-asher** [comment]
Also I get the same error on latest master.

**Comment by collincchoy** [comment]
Hi there,

This is actually an issue with newer versions of pytest having broken the vs code python extension.

Check out this issue here:
https://github.com/microsoft/vscode-python/issues/6990

Supposedly it's fixed in the insider version of the extension, but an easy workaround is just downgrade pytest to <5.0.1 so `pip install pytest==5.0.1`.

On the other hand, the CLI options dropping into node is a whole 'nother issue that I've also encountered and should probably be its own issue. It took me forever to track down this issue that mentions it.

**Comment by fmder** [comment]
Right pytest==5.0.1 fix the problem. Not sure if this issue should be closed as it is upstream?
