### ISSUE TITLE
copy and debuger doesn't work

### ISSUE THREAD

**Issue by liuyike233** [cdr/code-server#1092]
- `code-server` version: 2.1523 /1.38.1
- OS Version: ubuntu 18.04

## Description

1.the copy function in the terminal seems not work at all
2.the debuger for python doesn't work

**Comment by xunfeng1980** [comment]
huh

**Comment by khaled** [comment]
I get the following error when trying to copy:

<img width="718" alt="Screen Shot 2019-10-24 at 8 38 27 AM" src="https://user-images.githubusercontent.com/11412/67486311-cfb7aa80-f639-11e9-9025-0270fba11377.png">

**Comment by sr229** [comment]
@khaled if you're running it on non-`localhost` IP or non-`*.local` domains then you're encountering Chrome blocking Clipboard access.

**Comment by khaled** [comment]
@sr229 hmm, copy/paste does work in the editor though...

**Comment by code-asher** [comment]
Yeah the `writeText` error means the clipboard isn't supported because of the reasons mentioned by @sr229 but we might want to detect that case and show a better error message.

I haven't looked into why copy/paste works in the editor but not the terminal but I assume it's because the editor isn't using the clipboard API and instead something like `document.execCommand` which has certain limitations but I'm not sure why the terminal doesn't use the same method.

We could add the fallback ourselves but it's not a good idea to access `code-server` over insecure domains anyway so I'm not sure we should expend the effort. Service workers don't work over insecure domains either so other things will be broken as well.

**Comment by sr229** [comment]
Closing as by-design. This is beyond our control. If you need someone to raise this to, go to Chromium development or W3C.
