### ISSUE TITLE
Accessing web browser cookies in extensions

### ISSUE THREAD

**Issue by ppkwiatkowski** [cdr/code-server#1148]
Is there any way of accessing web browser cookies, in extension code?
I know that native vscode extension API doesn't support such things (yet?), but it would be very useful to allow code-server communication with other parts of the system.

**Comment by sr229** [comment]
Even VSO doesn't support this (since we use the same upstream), so no I don't think we support this, since there's really no use case for this.

**Comment by code-asher** [comment]
I'll mark this as a feature request. We have plans for client-side extensions to manipulate the DOM directly so it could be part of that. It could also be interesting to allow them to interact with a parent page from within an iframe. But yeah I'm not sure I see what the use for allowing access to cookies would be either.

**Comment by ppkwiatkowski** [comment]
The use case is to run authenticated http requests from extension, as authentication data is usually stored in the cookies.
Thanks for your answering!

**Comment by sr229** [comment]
> The use case is to run authenticated http requests from extension, as authentication data is usually stored in the cookies.
> Thanks for your answering!

Hmm, that is such a trivial use case considering its also invasive and VSO might also not support this as well. 

Definitely a interesting use case.

**Comment by code-asher** [comment]
Definitely interesting. I think I'm missing something though because why
would you want to make HTTP requests against code-server? The only thing
the HTTP requests provide is read-access to files which extensions can
already do by just performing an `fs.read`. :thinking:

**Comment by nhooyr** [comment]
We only want to support the VS Code extension API so isn't something we want to move forward with.

**Comment by lukasek86** [comment]
@code-asher @nhooyr 

Those _authenticated http requests_ could be external. E.g. browser is already authenticated by local systems and VS Code extension might also want to take benefit from that to integrate with services provided by these systems. But they require some kind of authentication token which is persisted in an inaccessible browser cookie and for now either the full authentication should be implemented in the extension (I imagine a potential user wouldn't be super happy to enter credentials for the second time) or token should be passed with some other means through a file on disk. The latter is the way to go I guess.

**Comment by code-asher** [comment]
Do you have any specific examples in mind of things extensions could do with the ability to make authenticated HTTP requests against code-server that they couldn't already do some other way?

**Comment by nhooyr** [comment]
I'm confused, why couldn't you just make the HTTP request? Credentials would be included in the cookie by the browser.

**Comment by code-asher** [comment]
If I'm not mistaken this is for making requests from the extension running on the server, e.g. from code running in Node. Not many extensions run in the browser context currently (via web worker) (actually it might be only the vim extension that runs client-side at the moment).

**Comment by nhooyr** [comment]
Ah I see, that makes sense. I think the move then would be just to run the extension on the client. How are we choosing at the moment? Is it hard coded for vim? @code-asher

**Comment by code-asher** [comment]
Yup, vim is hardcoded. Any extension marked as a `web` extension will also run in the browser, but the ability to run _any_ extension as a web extension was something we added to code-server (since we had to add fills for native Node calls like `fs.write` and such). That means such an extension would work in code-server but not in VS Code so it might not be a viable solution for extension authors if they want to support both.

I'm not sure what VS Code's long-term plan is for web extensions, they might just require that extensions that want to run in the browser only use the VS Code API and avoid any Node API. So if an extension today only uses the VS Code API and marks itself as `web` it might work in both code-server and VS Code although I haven't tested this. The `web` value seems to be undocumented as of yet. https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

Right now our criteria for whether to hardcode an extension to run on the client is based on performance. The vim extension can be rather laggy if it has to communicate with the server for every keystroke. I think in general it might be better to keep extensions on the server when possible to keep computation off the user's computer (save battery life, etc).

**Comment by nhooyr** [comment]
@ppkwiatkowski Can you mark your extension as a web extension and give it a shot?

**Comment by ppkwiatkowski** [comment]
@code-asher @nhooyr @lukasek86 thanks! I didn't know about this `web` parameter, looks interesting; will definitely give it a shot and let you know how it goes.

**Comment by lukasek86** [comment]
The discussion above has been informative indeed, thank you. Now that I understand more of this I have another question. Assuming the extension stays on the server (happens when `"extensionKind": ["workspace"]`) is there any way to peek into HTTP headers contained in request from a web browser running VS Code to its nodejs backend running code-server? Somewhere among them there is that token I'm so interested in.

**Comment by nhooyr** [comment]
There is no easy way at the moment.
