### ISSUE TITLE
Visual Studio Online - getAccessToken is not implemented

### ISSUE THREAD

**Issue by BirkhoffLee** [cdr/code-server#1150]
- `code-server` version: latest (Docker Hub: `codercom/code-server:latest`)
- OS Version: Host: Ubuntu 18.04.3 LTS
- Extension: https://marketplace.visualstudio.com/items?itemName=ms-vsonline.vsonline

## Description

<img width="516" alt="Screen Shot 2019-11-05 at 9 33 31 PM" src="https://user-images.githubusercontent.com/8148095/68212337-4aa69b00-0014-11ea-8ad5-5317f91d3acd.png">

## Steps to Reproduce

```
apt install -y bsdtar
wget -4 -O ms-vsonline.vsonline-1.0.1214.vsix https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vsonline/vsextensions/vsonline/1.0.1214/vspackage
bsdtar -xvf ms-vsonline.vsonline-1.0.1214.vsix
mv extension ../.local/share/code-server/extensions/ms-vsonline.vsonline-1.0.1214
mv extension.vsixmanifest ../.local/share/code-server/extensions/ms-vsonline.vsonline-1.0.1214/..vsixmanifest
```

and reload the page.

**Comment by code-asher** [comment]
I'm not sure it's possible for us to hook up code-server to VS Online
but we could certainly give it a try. But it does seem like at that point
you should just use VS Online directly? Or am I missing something?

**Comment by code-asher** [comment]
Doesn't this extension connect to VS Online? Which means you need to be
paying for VS Online in order to use it?

**Comment by BirkhoffLee** [comment]
VSO has an option to self-host, which is free

**Comment by code-asher** [comment]
Ahhhh I see. If you're self-hosting could you use code-server directly
on your host? In any case, I'll take a look and see if we can fix this.

**Comment by matmunn** [comment]
https://docs.microsoft.com/en-us/visualstudio/online/how-to/vscode#self-hosted

Self-hosted requires you to trigger it from within VS Code. I'd really like this functionality as well

**Comment by code-asher** [comment]
I'm still a little bit confused. Is the use case to host code-server on
a remote machine then use code-server on that remote machine to connect
to yet another remote machine that is hosting a self-hosted VS Online
instance?

And if so, could you run code-server directly on that second remote
machine instead of using VS Online?

I'll still take a look, just wanna make sure I understand the value so I
can prioritize appropriately.

**Comment by BirkhoffLee** [comment]
Let’s say I have a laptop and remote server A.

My laptop has VSCode installed, and A has code-server installed. 

The self-hosted VSOnline requires to be activated on a VSCode instance, which in case we’re using code-server here. After it’s activated, I can now simply use the VSCode on my laptop and use VSOnline to connect to A.

**Comment by code-asher** [comment]
Ahhhhhhh I gotcha. Thanks for that explanation.

**Comment by elgandoz** [comment]
Sorry to jump in this issue, but @BirkhoffLee I'm curious about the use-case:
Are you trying to use VS Code ("Classic" Electron Client) to connect to an instance of code-server?
Why not using VS Code with SSH Remote Development? Do you have any reason behind? I'm asking only to understand.
In my case, I use mainly code-server on one of the servers I'm working on because it has no outer internet access, therefore the installation of the packages required for SSH R.D. is not possible.
Although I would be very interested tin being able to use my code-server instance from the VS Code client...

**Comment by BirkhoffLee** [comment]
@elgandoz I’m not sure if you have ever tried the SSH remote but I’d say it feels like more of a SFTP client integrated with code editor and terminal. It’s pretty unstable on my side.

**Comment by nhooyr** [comment]
Can't really do this due to licensing restrictions.
