### ISSUE TITLE
Code-server can not install as desktop PWA in current version

### ISSUE THREAD

**Issue by tgly307** [cdr/code-server#1181]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: centOS 7, docker version 18.09.0

## Description

Code-server can be installed as desktop PWA in past version. But in current version, code-server can not be installed, the install icon in chrome address bar is missing. I found that there is no service worker in dev-tools/application.

## Steps to Reproduce

1. install code-server by docker image
2. open code-server in chrome and check

**Comment by sr229** [comment]
Unfortunately, this is a upstream issue, which we cannot solve by our own. If you think this also has the same behavior with VS Online, open an issue in Microsoft/vscode as well.

**Comment by geiseri** [comment]
Can you reference where this is upstream?  As far as I can tell it is an issue of a malformed manifest.

```
{
	"name": "code-server",
	"short_name": "code-server",
	"start_url": ".",
	"display": "standalone",
	"background-color": "#fff",
	"description": "Run VS Code on a remote server.",
	"icons": [{
		"src": "./code-server.png",
		"sizes": "384x384",
		"type": "image/png"
	}]
}
```

My command to start it is: `code-server --host=0.0.0.0 --auth=none --port=8080 --base-path=/code`  I am behind a reverse proxy then that will forward https://gateway.foo.com/code to the local docker on port 8080.

When I open the link the first thing is see is that the icon for `code-server.png` is not valid because it is looking for https://gateway.foo.com/code-server.png instead of https://gateway.foo.com/code/code-server.png.  In general, it looks like some of the earlier calls go to https://gateway.foo.com and not https://gateway.foo.com/code, but somehow the server still replies so it works, but it might confuse the workers. 

Is the upstream bug in `loader.js`?  As far as I can tell that is what registers the service workers.  It loads from `/` first and then later it will use the correct base path.

**Comment by code-asher** [comment]
Interesting, since the start URL is "." and you visit /code, that
resolves to /code-server.png. If you visited /code/ (trailing slash), it
would resolve to /code/code-server.png.

I think what we'll need to do is inject the base path into the manifest
before serving it.

**Comment by hmmhmmhm** [comment]
i found out what was presumed to be this issue in the latest code-server.

### Manifest information received from code-server on mac
> This json works very well normally.
```json
{
  "name": "code-server",
  "short_name": "code-server",
  "start_url": "./../../../../../../../../../../..",
  "display": "fullscreen",
  "background-color": "#fff",
  "description": "Run editors on a remote server.",
  "icons": [
    {
      "src": "./../../../../../../../../../../../static/4cd55f94c0a72f05c18cea070e10b969996614d2/usr/local/Cellar/code-server/3.12.0/libexec/src/browser/media/pwa-icon-192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "./../../../../../../../../../../../static/4cd55f94c0a72f05c18cea070e10b969996614d2/usr/local/Cellar/code-server/3.12.0/libexec/src/browser/media/pwa-icon-512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ]
}

```


### Manifest information received from code-server on windows
> This json detects grammar errors.
```json
{
    "name": "code-server-windows",
    "short_name": "code-server-windows",
    "start_url": "./../../../../../../../../../../../..",
    "display": "fullscreen",
    "background-color": "#fff",
    "description": "Run editors on a remote server.",
    "icons": [
        {
            "src": "./../../../../../../../../../../../../static/4cd55f94c0a72f05c18cea070e10b969996614d2C:\Users\metamorp\AppData\Roaming\npm\node_modules\code-server/src/browser/media/pwa-icon-192.png",
            "type": "image/png",
            "sizes": "192x192"
        },
        {
            "src": "./../../../../../../../../../../../../static/4cd55f94c0a72f05c18cea070e10b969996614d2C:\Users\metamorp\AppData\Roaming\npm\node_modules\code-server/src/browser/media/pwa-icon-512.png",
            "type": "image/png",
            "sizes": "512x512"
        }
    ]
}
```

I think path.resolve should be applied when writing the manifest.
