### ISSUE TITLE
code-server exits when refreshed during the login process

### ISSUE THREAD

**Issue by ywyz** [cdr/code-server#1205]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version:  Ubuntu 18.04.3 LTS by BandwagonHost

## Description

When the browse was loading the website, I try to stop the browser and reload the website because of slowly loading ,  The browser displays CONNECTION_REFUSED. And an the sametime  code-server on the server will be stoped liked press CTRL + C.
The server will show error informations while stoped reload the  code-server if the code server has been loaded

![20191201212735](https://user-images.githubusercontent.com/23413387/69914713-222e8700-1482-11ea-99cf-610c229e149c.jpg)

## Steps to Reproduce

1. open code-server in new tab or reload while code-server already load
2. stoped the browser load

**Comment by xapenny** [comment]
Me too, tried Ubuntu 16.04 LTS & 18.04 LTS. Nether works.

**Comment by sr229** [comment]
Can't replicate issue, are you sure nothing else runs on port 443?

**Comment by ywyz** [comment]
> Can't replicate issue, are you sure nothing else runs on port 443?

Nothing  else runs on port 443.

After OS reboot
![AfterOSReboot](https://user-images.githubusercontent.com/23413387/70048862-4915c600-1606-11ea-87df-9a7dad416302.jpg)

After Code-server start
![AfterCodeserverStart](https://user-images.githubusercontent.com/23413387/70049177-128c7b00-1607-11ea-92d1-f1efc8a5f2c6.jpg)


![深度录屏_选择区域_20191203195923](https://user-images.githubusercontent.com/23413387/70049396-90508680-1607-11ea-8340-3e2cdfde19cb.gif)

**Comment by sr229** [comment]
Made the issue clear now, @code-asher this might be a show breaking bug.

**Comment by code-asher** [comment]
I've seen this before but have been having a hard time replicating it.

**Comment by code-asher** [comment]
Related: https://github.com/cdr/code-server/issues/1009

**Comment by LesegoGomolemo** [comment]
I'm having a similar issue. It closes just as I am entering my login password. The only parameters I use are the --port, --cert and --cert-key.

This is on Ubuntu 18.04.3 LTS as well.

**Comment by antofthy** [comment]
We are also experiencing this problem. Only during startup.   No obvious errors, either on command output, or in the "remoteagent.log" log file, with --verbose enabled.

**Comment by antofthy** [comment]
After trying the latest version 2.1692-vsc1.14.1 the crash problem on start up still remains.

**Comment by code-asher** [comment]
Does this only happen when using a certificate? I haven't been able to
replicate with HTTP or with the built-in certificate generation so maybe
it has something to do with certificates generated a certain way?

**Comment by antofthy** [comment]
The setup uses a self signed certificate (HTTPS)...  
    `code-server .  --port 8443 --auth password --cert '' --verbose  --disable-telemetry`
Password is supplied via the environment variable $PASSWORD

**Comment by sr229** [comment]
I also noticed this on the `onodera` test server as well @code-asher, it seems 2.1698 crashes if we login or refresh. You can try replicating it there.

**Comment by code-asher** [comment]
@sr229 Is there anything additional you did to make it crash? I ran the
following on the test server but didn't experience any crashes:

`code-server --cert --verbose`

There must be something wrong with our TLS socket proxy. It creates a
socket at /tmp/code-server/tls-proxy and then pipes that socket with the
TLS socket coming from the browser. The non-TLS side is then passed into
the extension host, all because TLS sockets can't be moved into another
process (as far as I know).

If the socket is already in use it should keep trying with an
incrementing number appended but maybe that logic isn't quite right? I
tried spawning two instances and logging in multiple times to each but
still no crashes.

A reverse proxy is definitely the more stable scenario if that's an
option for anyone running into this issue.

I believe the extension host is capable of using stdio instead of being
passed a socket so maybe we can resolve this by piping the stdio with
the TLS socket and avoid creating the proxy altogether (assuming that's
even the source of the issue but if this only happens with TLS then it
seems probable).

**Comment by antofthy** [comment]
I have had a report that this happens more often when using firefox.

**Comment by sr229** [comment]
@code-asher shouldn't we be creating a TLS socket at `/var/run`? I think the TLS socket should be something that should be created to something that most sockets would be created.

**Comment by code-asher** [comment]
Is /var/run writable? On my system it's only writable by root. The only
way I've used it in the past is with a systemd service.

For what it's worth, VS Code also creates their sockets in /tmp.

I repeated all my tests with Firefox but have still had no luck
replicating the crash. :/

**Comment by nhooyr** [comment]
See #1009
