### ISSUE TITLE
How to install Remote Development extension?

### ISSUE THREAD

**Issue by lujo777** [cdr/code-server#1256]
I tried using search to find this extension, but it not found. 
Also, there is no extension from microsoft.

**Comment by balazssoltesz** [comment]
code-sever has it's own marketplace and this is not equivalent with the vscode's one. There are no packages from microsoft here because of licencing issues. However u can install extensions manually. Download the .vsix file from vscode marketplace (https://marketplace.visualstudio.com/vscode) upload it to your server and in code-server u will find a menuitem at extensions section "Install from vsix...".  That's all.

**Comment by nhooyr** [comment]
Thank you @balazssoltesz

**Comment by sledgeha1** [comment]
I tried to install ms-vscode-remote.vscode-remote-extensionpack-0.20.0.vsix as described. But i get the warning on installed expansion page: 
"This extension has defined that it cannot run on the remote server"

Did someone manage to make this extension working on code-server?

**Comment by HarvsG** [comment]
I have installed it using the vsix but the tab does not appear in the sidebar

**Comment by code-asher** [comment]
@HarvsG The remote extensions appear to be designed in a way that won't work in code-server. Check out https://github.com/cdr/code-server/issues/1315 for more info.
