### ISSUE TITLE
Update tag for latest release?  (2.1698)

### ISSUE THREAD

**Issue by robiupui** [cdr/code-server#1282]
This is extremely minor and dumb, but can the tag for the 2.1698 release be updated to match previous tag syntax that includes the VS Code version?  If so, the tag should be **2.1698-vsc1.41.1**

I teach a course using GCP where I have students install code-server in their Cloud Shell and I used the [excellent step-by-step guide in this article](https://medium.com/google-cloud/how-to-run-visual-studio-code-in-google-cloud-shell-354d125d5748) to build my tutorials.

Now that the tag doesn't include the full version, the article and the scripts break.

Thank you in advance for your consideration!

<img width="718" alt="Screen Shot 2020-01-18 at 9 30 20 AM" src="https://user-images.githubusercontent.com/3439633/72665370-ea4db580-39d5-11ea-997c-6821ed025ee7.png">

**Comment by sr229** [comment]
Heya, I'm the one that wrote the new deployment strategy for code-server. Not really sure why there was discrepancy over that. I suggest just compensate for the new versioning syntax, since we launch by tags now compared to manual releases before.


The reason there's a difference right now with the tag and the name is because the release name is always suffixed by the `$VSCODE_VERSION` variable. so it would be `$TAG-vsc$VSCODE_TAG`. We've switched all of our scripts to do that. So if we replace `$TAG` with the previous tag version, this will create a redundant entry.

**Comment by mirekphd** [comment]
The problem is that all `code-server` releases since March 2019 were tagged in such a way, that the filename of the installation package could be retrieved from the latest tag. Not anymore...

I can only image that this innocuous change broke a lot of automated builds. It certainly did break one of ours...

If you insist on the shorter tag from now on, then please remove anything apart from this shorter tag from the file name, to make the filename predictable again (e.g. `code-server2.1698-linux-x86_64.tar.gz`)

**Comment by sr229** [comment]
> The problem is that all `code-server` releases since March 2019 were tagged in such a way, that the filename of the installation package could be retrieved from the latest tag. Not anymore...
> 
> I can only image that this innocuous change broke a lot of automated builds. It certainly did break one of ours...
> 
> If you insist on the shorter tag from now on, then please remove anything apart from this shorter tag from the file name, to make the filename predictable again (e.g. `code-server2.1698-linux-x86_64.tar.gz`). The current filename (here: `code-server2.1698-vsc1.41.1-linux-x86_64.tar.gz`) is now based on the release not the tag, and for determining latest version we use tags (as the only robust source we found for Github assets).

Not a chance. This is determined by the nbin build system and we don't want to change that.

**Comment by mirekphd** [comment]
Fair enough. So it looks like the only workaround now is to find out the latest tag for `microsoft /
vscode` as well (currently 1.41.1), and combine it with your latest tag.

**Comment by sr229** [comment]
@mirekphd However I could raise it to the team to make sure the automation experience will be the same.

**Comment by mirekphd** [comment]
Fair enough. So it looks like the only workaround now is to find out the latest tag for `microsoft /
vscode` as well (currently 1.41.1), and combine it with your latest tag.

**Comment by mirekphd** [comment]
So the output of `code-server --version` will stay as it was before? (different from what Github API and `git describe --tags` return)? 

I also noticed that in the URL linking to the code-server zipped binary the folder changed, but not the filename or the internal (zipped) folder name.

**Comment by sr229** [comment]
@mirekphd yep, our build system is designed to always suffix the vscode version.

**Comment by code-asher** [comment]
My sincere apologies to all the articles and builds I've broken with the
new tag. We were in a weird spot because previously the tags were
generated from the code so they were more or less guaranteed to match
the actual VS Code version in use but now that it's done manually the
only guarantee is human which isn't quite as reliable.

Additionally, our long-term vision is to have code-server less directly
tied to the version of VS Code packaged with it so maybe it would be
best to drop the `vsc` portion from everything and list the VS Code
version separately in places like `--version` and the `About` dialog?

**Comment by mirekphd** [comment]
Never mind, I managed to code for the discrepancy, but the workaround is rather brittle, as it relies on the latest `microsoft/vscode` version being used in the file name of `code-server` zipped binary. Some day when you decouple these two latest versions (`code-server` and `vscode`), e.g. to pin `vscode` at some older version (should the latest one be faulty), I might run into troubles.

**Comment by nhooyr** [comment]
Is there anything that needs to be done here or can it be closed @code-asher?

**Comment by nhooyr** [comment]
@code-asher is going to add the tag back to prevent confusion.

We're still going to remove it in the future at some point.

**Comment by mirekphd** [comment]
As far as I'm concerned, the fewer breaking changes, the better, including
not reverting to the status quo (ie keeping the current shortened tag,
which I've already adapted to, and so have probably others (?)).

**Comment by code-asher** [comment]
Ah I was going to add the tag in addition to the existing one but upon
further thought I guess that wouldn't fix anything because the whole
problem is that /latest points to the tag which is then used to build
the name of the archive to download, right?

**Comment by mirekphd** [comment]
Yes, the /latest points to the code-server tag, buy downloaded archive
contains an extra tag from another repo (microsoft/vscode). Both tags can
be queried using the API or git, and combined into the archive name. Not
the safest solution, as it relies on the Microsoft's tag also being always
latest.

**Comment by code-asher** [comment]
That makes sense. The next version of code-server will drop the VS Code portion entirely. We'll keep with the `#.####` format. I'll go ahead and close I suppose since there's nothing to act on at the moment.

**Comment by mirekphd** [comment]
Still waiting for the `Pre-relese` status of version 3.0.0 to change into `Latest version` to be able to revert all the hacking required to auto-install the "twin" `2.1698-vsc1.41.1 / 2.1698` version :)
