### ISSUE TITLE
Security Recommendations?

### ISSUE THREAD

**Issue by nickian** [cdr/code-server#1283]
I was curious if there were any security recommendations running code server on a server with important data.

1. Should we avoid running it as the root user? I ran into issues when trying to run it as www-data.
2. Is there any protection in place against brute-force on the login screen?
3. Is there any known technique to integrate this with an existing web application's authentication system?
4. How big of a liability is it to have a password in an environment variable set by systemd?

Currently, I have the password on code-server set up and running by systemd as root, but I also have it behind an Apache reverse proxy with basic http authentication. Is this a good idea?

Thanks!

**Comment by sr229** [comment]
@nickian Security when running a service like code-server entails some common sense with Unix/Linux security. So you made some bad practices in here:

- You have not set fail2ban for your service to prevent brute forcing attempts.
- Running user for any public web service unless its a reverse proxy is considered dangerous. That's bad practice as well.

- While plaintext password authentication we provide is quite strong on strong scenarios, we provide no gurantees of protection with brute force attacks. Please use a more sophisticated authentication method. We have quite few in one of the pinned issues.

Our recommendation is basically just have some common sense of security. If it really needs to be locked down, lock it down.

**Comment by nhooyr** [comment]
> Should we avoid running it as the root user? I ran into issues when trying to run it as www-data.

If you don't want password less sudo, you should avoid running as root. If you have passwordless sudo as in the default image, then it makes little difference since one can easily escalate to root via `sudo`. I'd also recommend enabling docker user name spacing.

I'll add this to the FAQ I'm writing.

> Is there any protection in place against brute-force on the login screen?

That's a great question. @code-asher do we have any brute force protection? If not, we need to add it.

> Is there any known technique to integrate this with an existing web application's authentication system?

You'd disable code-server's authentication and use a reverse proxy.

> How big of a liability is it to have a password in an environment variable set by systemd?

Not a big deal as long as you use containers to separate users. If you do not, then it is a problem as any process can read another process's environment.
