### ISSUE TITLE
Scraper dashboard for extensions

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1299]
Need a dashboard for users to request an extension be refreshed and improve the existing service.

**Comment by nhooyr** [comment]
@wbobeirne

**Comment by nhooyr** [comment]
> The manual installation is definitely a problem, we forgot to implement the endpoint properly in the extension marketplace.

#1173

**Comment by frank-dspeed** [comment]
@nhooyr watch and join my effort https://github.com/cdr/code-server/issues/1322

**Comment by sr229** [comment]
We do not plan to join in any efforts as we have our own plans of providing extensions

**Comment by nhooyr** [comment]
Of course if the VS Code team allows it, we have no problem sharing extensions.  But they are unlikely to get on board. We appreciate your efforts @frank-dspeed.

**Comment by frank-dspeed** [comment]
@nhooyr i know many of the team members they are not evil but they have some rules to follow so we need to have patience much patience and follow the process needed but i see at all no blocker for this as we all work on the same vision.

**Comment by omfgnuts** [comment]
@nhooyr could you please reopen, #1298 as it still needs investigation, I didn't use the extension from the built-in marketplace. Thank you!

**Comment by sr229** [comment]
@omfgnuts All done, GH-1298 is reopened.

**Comment by nsadeh** [comment]
How can I submit Scalameta.metals to the extensions marketplace clone?

**Comment by nhooyr** [comment]
We'll take care of it. @cmoog

**Comment by cmoog** [comment]
@nsadeh Done! 👍

**Comment by nsadeh** [comment]
Thanks, but it’s not compatible with he current version of VSCode (I get
`Unable to install 'scalameta.metals' extension because it is not
compatible with the current version of VS Code (version 1.41.1).`). I am
using the latest stable release of code-server.

I ended up figuring out the API for the extensions market place and
installing an older version of the extension but would be nice for this to
work out of the box if possible so I can achieve feature parity with
Microsoft VSCode Online.

I don’t know if the new releases are compatible with
https://www.digitalocean.com/community/tutorials/how-to-set-up-the-code-server-cloud-ide-platform-on-ubuntu-18-04
But if the Coder DO droplet has the latest version of VSCode and can be
setup to run perpetually I made give that a go.

**Comment by nsadeh** [comment]
Even installing manually, metals does not work with code-server so I am unable to do meaningful Scala development.

**Comment by kylecarbs** [comment]
What doesn't work @nsadeh ?

**Comment by nsadeh** [comment]
@kylecarbs it just doesn't load/import Scala projects/do anything it's supposed to do.

As far as the DO droplet goes, it also doesn't work but I will file a separate issue for that.

**Comment by kylecarbs** [comment]
Real strange. Is there anything in your console output?

**Comment by nhooyr** [comment]
@nsadeh Please do file a new issue and we'll try our best to help you out.

**Comment by izzues** [comment]
Sorry if I'm missing something, but where do I report missing extensions currently? Should I open new issues here?

Btw, apparently missing: https://github.com/koog1000/vscode-fossil

**Comment by nhooyr** [comment]
@izzues Please open a new issue yes!

**Comment by cmoog** [comment]
Currently, there are no plans for move forward with releasing this.

**Comment by nhooyr** [comment]
Sorry, seems to have been some misunderstanding.

**Comment by code-asher** [comment]
Closing since we'll be moving to OpenVSX.
