### ISSUE TITLE
Ratelimit code-server password auth

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1320]
No rate limiting at the moment, which is embarrassing.

**Comment by frank-dspeed** [comment]
lets take this more far lets strip out of this code anything none http2 related and let this run only on http2 even with a standard public cert then we will publish some default configuration for nginx and haproxy this will cover all needs we don't need to integrate the server part there are better servers around then our nodejs implamentation.

and i want to default to http2 because when this runs in a shared container environment the traffic between lb or proxy is encrypted on the network level
