### ISSUE TITLE
Python: Unable to select, enable or run linting 

### ISSUE THREAD

**Issue by Trinitrogen** [cdr/code-server#1360]
- `code-server` version: 2.1698-vsc1.41.1
- OS Version: Ubuntu 18.04.3 LTS
- Extension: Python 2020.1.58038

## Description

Unable to select a linter, get the error "Unable write to Folder Settings because no resource is provided"

## Steps to Reproduce
From Command Pallet, select "Python: enable linting" and then selecting "on" gives me the above error. The same scenario will happen if I "Enable Linting" or "Run Linting"

**Comment by kylecarbs** [comment]
Works for me. Do you have a folder open?

**Comment by vinay-swamy** [comment]
- `code-server` version : 2.1698-vsc1.41.1
- OS version: CentOS 7
- Extension: Python 2020.2.63072

I'm running this in singularity, not docker fyi
Hi, I'm Having this same issue. I have a workspace open, and within settings it says linting is on both globally and in the workspace. But when I try to enable listing I get the error message `Unable to write to Folder Settings because no resource is provided.`

**Comment by code-asher** [comment]
Would you be able to try this out in v3 and see if the problem persists?

**Comment by vinay-swamy** [comment]
That did the trick. Thank you!
