### ISSUE TITLE
Unable to paste to terminal

### ISSUE THREAD

**Issue by sh7dm** [cdr/code-server#1402]
OS: Ubuntu 19.10, x86_64, `code-server` is running in Docker container
Browser: Firefox 74
Version: latest from Docker, pulled today

1. I've got a command I want to execute in clipboard
2a. I press Ctrl+Shift+V, just as in VS Code terminal, it doesn't work
2b. I try right-clicking the terminal, I get this:
![image](https://user-images.githubusercontent.com/19504461/76138173-37551c00-6056-11ea-9b98-e506ea770796.png)
As you can see, no `Paste` option
2c. For last try I pressed Ctrl+V, and I got `^V`, as usual.
3. In none of these cases command is pasted.

**Comment by sh7dm** [comment]
Maybe this's related to #1106, since I use http to connect to editor:
![image](https://user-images.githubusercontent.com/19504461/76138203-9f0b6700-6056-11ea-894c-85877b14c8a4.png)

**Comment by sh7dm** [comment]
Updated container config, accessing as `localhost:8080`, it doesn't paste, but `localhost` is a secure context for browser.

**Comment by sh7dm** [comment]
I checked, it works okay in Chrome, but doesn't in Firefox.

**Comment by kylecarbs** [comment]
Hm, I thought firefox worked as well. Any ideas @code-asher ?

If it doesn't work in Firefox, it might not be a bad idea to make a table for features available in each browser.

**Comment by code-asher** [comment]
Yeah, it's a bit of a mess on Firefox.

Firefox doesn't support the clipboard API so it's not possible to do
anything but a native paste (which is why there's no right-click menu
for pasting).

Unfortunately while Firefox will perform a native paste with `Ctrl+v`,
that keybinding already has a different assignment in the terminal so it
can't be used.

Normally `Ctrl+Shift+V` would also perform a native paste but in Firefox
that only works in `contenteditable=true` elements for some reason, and
the terminal doesn't use that (it probably should though).

`Shift+Insert` does usually perform a native paste in Firefox though so
that might work for you.

**Comment by sh7dm** [comment]
@code-asher a solution for me was clicking on the mouse wheel, it performs native paste in FF

**Comment by code-asher** [comment]
Oh yeah that's great; I'd forgotten about that.

**Comment by code-asher** [comment]
I'll go ahead and close this in favor of #1106. I'll edit it a little to reflect better the current situation.
