### ISSUE TITLE
Unknown connection token.

### ISSUE THREAD

**Issue by Grimeton** [cdr/code-server#1407]
Hello,

when building the server with your repo, it starts up and everything, but then the browser and the server are not able to handshake the web socket tunnel. It always fails with "Unknown connection token".

It's always the same. Looks like this in the browser's debugger:

![image](https://user-images.githubusercontent.com/2773919/76261128-9cc52a80-6259-11ea-8cc6-b2d6b069d6e8.png)

Any hints?

KR,

G.

**Comment by kylecarbs** [comment]
Hm. Which version are you using?

**Comment by Grimeton** [comment]
Latest. Just checked out the repo and built.

**Comment by Grimeton** [comment]
One thing... When building I have to use react-scripts@2.1.8 because it won't build with the latest version... I wonder how that's fixed on your side...

**Comment by code-asher** [comment]
That's odd, I don't think `react-scripts` is in our dependencies. I just checked the `yarn.lock` but didn't see it.

Typically I've seen the unrecognized token error occur when VS Code crashes for some reason and then the browser tries to reconnect but the token is no longer valid. Is there any output in code-server's output that might indicate a crash? I've seen it happen fairly often due to issues with native node modules which can be fixed by going into `lib/vscode` and running `npm rebuild`, but our build scripts should already be doing that for you.

**Comment by lakshmanpasala** [comment]
There are breaking changes between v2 and v3. Deleting your `.local/share/code-server` before starting the server should do the trick.

**Comment by lakshmanpasala** [comment]
I was facing the same issue with v3 and updating node from 10 to 12 fixed it.

**Comment by code-asher** [comment]
Oh yeah that makes a lot of sense. code-server only supports Node 12
onward. v10 just crashes on some string assertion.

**Comment by Grimeton** [comment]
Hey,

I'm going to build the latest version now and come up with a full build log. Sorry for the late reply, we got a little virus situation over here.

Stay well!

Cu

**Comment by Grimeton** [comment]
Switching to nodejs 12 seems to have fixed it.

**Comment by nhooyr** [comment]
> And for the love of god make the login/password request work in your official docker image. It's broken.

Could you elaborate? Does the generated password just not work?

**Comment by nhooyr** [comment]
Just tested, seems to work fine,

**Comment by Grimeton** [comment]
Oh, sorry. I'm talking about the askpass situation with git. In your image the askpass command is missing and it just errors out when you have to use a username/password to clone a repo.

**Comment by nhooyr** [comment]
What package is the askpass command in? I believe this is just https://github.com/cdr/code-server/issues/695#issuecomment-588603853

**Comment by nhooyr** [comment]
Opened https://github.com/cdr/code-server/issues/1464 as well

**Comment by Grimeton** [comment]
When I build your version of code-server myself, a prompt shows up at the top of the UI and it asks me for username/password.

It's the same position as the default input when pressing CTRL+ SHIFT + P

Don't forget that my last experience with your image is 20 days old. Maybe this has already been fixed.

**Comment by nhooyr** [comment]
Can you screenshot this prompt? Nothing changed as far as I know.

**Comment by Grimeton** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/2773919/77930141-cac2eb00-72aa-11ea-8d03-692ab5120a03.png)

![image](https://user-images.githubusercontent.com/2773919/77930153-cf879f00-72aa-11ea-94c2-4ac29bd6a7a8.png)

**Comment by code-asher** [comment]
Closing since the original issue was resolved by upgrading to node 12 which at the moment is the minimum version we require.

For some context on the askpass issue, in version 2.1698 we bundled everything into a single binary that contained a patched Node which could import JavaScript from within the binary. Unfortunately that didn't work when trying to execute something that wasn't JavaScript, such as the git extension trying to run `askpass.sh` or todo-tree trying to run `rg` (ripgrep).

In v3 we don't bundle anymore so these types of issues should be resolved.
