### ISSUE TITLE
docs for building a custom docker image

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#145]

**Comment by ymolists** [comment]
I am using the docker file and i am noticing that this might not be the best way for a dockerfile that is meant to only build locally. Would it make sense for example to create a new one say Dockerfile.build ?
you could for example mount the source code locally each time instead of copying it ? that would make the dockerfile maybe faster to build since the layers would not keep changing ?

**Comment by nhooyr** [comment]
What do you mean only build locally?

**Comment by nhooyr** [comment]
I don't believe we can mount stuff in when building a container. It has to be copied.

Furthermore, you don't see any of these artifacts in the resulting image because we're using a multi staged build.

**Comment by ymolists** [comment]
I think we are mixing 2 separate use cases

1) someone who wants to hack on the code and has to build the code again and again in their environement

2) someone who wants to just build a binary.

If someone is in 1) then it makes sense to not copy the source code in the image but mount it later when the container is started . The dockerfile would only make sure the used binaries are always the same across the possible combinations of environments and should make supporting it easier.

**Comment by nhooyr** [comment]
Do you want a `build.sh` script to build the code instead of a Dockerfile?

I'm not sure I see the value here. @kylecarbs do we have support for incremental compilation or will each build still take 20m?

**Comment by ymolists** [comment]
Well maybe you can document what you do now :-) i imagine it does not take 20m to build it incrementally.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
