### ISSUE TITLE
Python debugger not working

### ISSUE THREAD

**Issue by sponde25** [cdr/code-server#1476]
I installed the release 3.0.1 and installed the python extension from the marketplace. I am observing the behaviour described here: https://github.com/microsoft/vscode-python/issues/7927

**Comment by cmoog** [comment]
Have you tried the workaround described here: https://github.com/microsoft/vscode-python/issues/7836#issuecomment-540350986

The only difference is instead of `$HOME/.vscode/extensions/ms-python..` you'll need to put `requirements.txt` in `.../coder-server/lib/vscode/extensions/python` wherever you installed code-server.

**Comment by sponde25** [comment]
After putting the `requirements.txt` in `code-server/lib/vscode/extensions/python/` things work as expected. Thanks for the help!
