### ISSUE TITLE
discarding socket connection: vscode is not running

### ISSUE THREAD

**Issue by JayXon** [cdr/code-server#1484]
Keep getting this after updated to 3.0.2

**Comment by pr1metine** [comment]
Elaborate, @JayXon...

**Comment by JayXon** [comment]
I got a prompt to update to 3.0.2, so I clicked it and it says update failed, log only has this error, and webpage says "Attempting to reconnect..."
I tried to delete the code-server directory entirely and download from release manually, but still the same.
```
info  code-server 3.0.2 e480f6527e11344a7c69b7cd024bce9379cea7f0
info  HTTP server listening on http://127.0.0.1:8080
info    - Using custom password for authentication
info    - Not serving HTTPS
info  Automatic updates are enabled
info  SSH server listening on localhost:43289
warn  discarding socket connection: vscode is not running
warn  discarding socket connection: vscode is not running
warn  discarding socket connection: vscode is not running
warn  discarding socket connection: vscode is not running
warn  discarding socket connection: vscode is not running
warn  discarding socket connection: vscode is not running
warn  discarding socket connection: vscode is not running
...
```

**Comment by code-asher** [comment]
Ah, that's probably because you need to refresh the page. It's trying to connect to the old instance but it's no longer running. Refreshing will start a new instance and the new page will connect to it.

Unfortunately at the moment there's no support for reconnecting when code-server restarts (like what happens when updating) which is why this is necessary.

The "update failed" message is a bug and will be fixed very soon.

**Comment by JayXon** [comment]
Refreshing did fix it! Thank you! How come I didn't think of that...

**Comment by pr1metine** [comment]
Glad to here that.
