### ISSUE TITLE
Not arm64 format for the arm64

### ISSUE THREAD

**Issue by Gumbraise** [cdr/code-server#1504]
I posted a post on Reddit and on the Discord but i didn't get any answers..
So, I get a ```exec format error``` when I execute ``./code-server`` and when a launch it with docker, I get ```standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size```
So, how can I do to launch the software on my RPi4 ?
Fix the bug. Thanks

**Comment by pr1metine** [comment]
Are you using standard Raspbian?

**Comment by Gumbraise** [comment]
Sure!
```
Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 4.19.97-v7l+
Architecture: arm
```

**Comment by pr1metine** [comment]
Ahh, check out #35 . Raspbian isn't arm64 (or aarch64) because of its 32-bit kernel. I tried to switch to the 64-bit one but it didn't work either (see [this](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=250730)).

In order to run code-server on your Raspberry Pi you are **required to install a arm64 OS** like [Ubuntu Server](https://ubuntu.com/download/raspberry-pi/thank-you?version=18.04.4&architecture=arm64+raspi3).
Alternatively if you want a gui you could run [Ubuntu Mate](https://ubuntu-mate.org/raspberry-pi/ubuntu-mate-18.04.2-beta1-desktop-arm64+raspi3-ext4.img.xz).

**Comment by pr1metine** [comment]
Note that running Ubuntu Server might not be compatible with your current RPi setup.

**Comment by Gumbraise** [comment]
Ok thanks

**Comment by TechLevelZero** [comment]
The issue with raspbian even with a 64-bit kernel is it still runs a 32-bit userspace.
You can get round this by using 'schroot' and setting up a 64-bit userspace in raspbian and running docker/code-server as that user

**Comment by pr1metine** [comment]
Thank you @TechLevelZero

**Comment by nhooyr** [comment]
Also see https://github.com/cdr/code-server/issues/1337#issuecomment-622457413
