### ISSUE TITLE
Strip double slashes in request URL

### ISSUE THREAD

**Issue by kylecarbs** [cdr/code-server#1529]
See https://github.com/cdr/code-server/issues/1461#issuecomment-605528454.

https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#request-matching

**Comment by nhooyr** [comment]
Should be done now that we use express instead. cc @code-asher

**Comment by code-asher** [comment]
If I recall correctly these were generated by VS Code actually. They have URLs like this:

```
https://<domain>/webview/vscode-resource/file///<path>
```

These resolve just fine normally but I guess the proxy in question errors on these for security reasons.

**Comment by nhooyr** [comment]
Should we keep this open then?

**Comment by nhooyr** [comment]
Tbh, I think the proxy needs to be fixed. I don't think we should support a buggy proxy.

**Comment by code-asher** [comment]
Supposedly it's a security feature so they probably wouldn't change it.

```
Un-normalized requests are automatically rejected by default
```

I agree with your sentiment though. It feels unfortunate we'd have to add to our patch to work around the quirks of a specific proxy.

**Comment by nhooyr** [comment]
> I agree with your sentiment though. It feels unfortunate we'd have to add to our patch to work around the quirks of a specific proxy.

Problem is the proxy is just wrong. There's nothing wrong with a unnormalized request in general. Only when `..` is involved. i.e double slashes could just be a typo.

Go's standard library `Mux` sanitizes the request path before passing it to you. That way your code doesn't have a security vulnerability but can still handle unnormalized requests as expected.

**Comment by code-asher** [comment]
My bad, I didn't mean to give the impression they were doing the right
thing or to argue in their behalf, the point I was trying to make is
that it seems unlikely the proxy would ever get "fixed" since this seems
very purposeful (just a guess on my part though). So if we close this
with the assumption it'll get fixed on their end that might be
misleading. But if we close it because we just don't want to support it
then that sounds good to me. :)
