### ISSUE TITLE
Java Extension Pack (vscjava.vscode-java-pack) plugin not there

### ISSUE THREAD

**Issue by GalacticLion7** [cdr/code-server#1595]
Some plugins like vscjava.vscode-java-pack (Java Extension Pack) are not there. I can't even install it with `ext install vscjava.vscode-java-pack`.

**Comment by cmoog** [comment]
Thank you for bringing this to our attention.`vscjava.vscode-java-pack` is now available in our marketplace. Let me know if you have any further issues and I'll reopen this.

**Comment by GalacticLion7** [comment]
But why wasn't vscjava.vscode-java-pack already there? Do you have to add extensions manually?

**Comment by KolyaKorruptis** [comment]
@GalacticLion7 A lot of extensions are missing. The point that isn't clearly communicated here is that code-server doesn't serve the VSCode product that everyone knows.
Instead it  serves **VSCode OSS**, which is the open source base that the Microsoft product is built on.

[VSCode OSS is missing some important features](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code
) that use proprietary code and MS services, including access to the Microsoft marketplace. @cmoog's reply suggests that they have created a mirror of the MS marketplace to connect to. Because VSCode without extensions is almost useless.
And that mirror is missing a lot of extensions.

Please correct me, if I'm wrong @cmoog.

**Comment by cmoog** [comment]
@GalacticLion7 @KolyaKorruptis This is correct. Please reference: https://github.com/cdr/code-server/blob/master/doc/FAQ.md#whats-the-deal-with-extensions
