### ISSUE TITLE
Support ANSI Color in 'Debug Console'

### ISSUE THREAD

**Issue by cospotato** [cdr/code-server#1610]
### In code-server

![image](https://user-images.githubusercontent.com/7987906/81377301-c7d3d980-9137-11ea-8047-94431e7c2f75.png)

### Expect

![image](https://user-images.githubusercontent.com/7987906/81377528-4466b800-9138-11ea-87f2-8250d56f67b2.png)

  Thanks for your works!

**Comment by code-asher** [comment]
Interesting, the `color` package seems to be disabling the colors because there isn't a tty (https://github.com/fatih/color#disableenable-color). Tested by setting `color.NoColor = false` which forces the colors to appear. Local VS Code must use a tty while remote doesn't, so maybe we can just patch it to use a tty.

**Comment by cospotato** [comment]
> Interesting, the `color` package seems to be disabling the colors because there isn't a tty (https://github.com/fatih/color#disableenable-color). Tested by setting `color.NoColor = false` which forces the colors to appear. Local VS Code must use a tty while remote doesn't, so maybe we can just patch it to use a tty.

Yes! You are right!
