### ISSUE TITLE
Slow extension: CamelCaseNavigation

### ISSUE THREAD

**Issue by TobiaszCudnik** [cdr/code-server#1663]
When using the [CamelCaseNavigation](https://github.com/maptz/Maptz.VSCode.Extensions.CamelCaseNavigation) extension you can notice:
- slow response (delay)
- key repeat issues (you can see the caret going back-and-forth)

This doesnt happen on a native vscode. [Related ticket on the extension's tracker](https://github.com/maptz/Maptz.VSCode.Extensions.CamelCaseNavigation/issues/32).

code-server: 3.2.0

**Comment by code-asher** [comment]
Might need to make this one run on the client side instead of the server.

**Comment by TobiaszCudnik** [comment]
> Might need to make this one run on the client side instead of the server.

Any hints on what decides about where an extension works? In this case it uses `vscode.commands.registerCommand`. Do you have RPC proxies on certain objects, eg the `ITextModel`?

**Comment by code-asher** [comment]
Yup, there are indeed proxies for the entire API and all the arguments it takes. The proxies are used for both the server-side extension host and the browser extension host so they should behave the same in theory (there are some differences though). On the browser side we additionally proxy Node API calls (like `fs.write()`).

There's a setting in the package.json of an extension that specifies whether it runs on the web (`"extensionKind": "web"`). I set that with this plugin but there's an error when the browser downloads the extension to run on the client. It seems to be making a request against `vscode-remote://` instead of `http://` which obviously won't work but I haven't yet looked into why. The Vim extension works fine on the client though so I'm not sure why this one doesn't. :thinking:

**Comment by code-asher** [comment]
Ahh, I was remembering incorrectly; `web` extensions run in VS Code's provided framework by default, not ours (and theirs only supports a subset of features). To run it in ours the only way currently is to hardcode the extension name like we do with the `vscodevim.vim` extension. 

I tried it out and it seems to work fine so I think that's what we should do. Or maybe we should extend `extensionKind` to accept something like `worker`, then users can set that in their settings to force an extension to run client-side.

**Comment by code-asher** [comment]
Now that VS Code has their own web extension support and we've removed ours in favor of that this will need to be done upstream in the `CamelCaseNavigation` extension.
