### ISSUE TITLE
Add Bookmarks extention to the marketplace

### ISSUE THREAD

**Issue by gyzerok** [cdr/code-server#1711]
- [x] Extension name: Bookmarks
- [x] Extension GitHub or homepage: https://github.com/alefragnani/vscode-bookmarks

**Comment by cmoog** [comment]
It looks like the core package included as a submodule is [closed source](https://github.com/alefragnani/vscode-bookmarks-core). Because of this, we are unable to build the `.vsix`. Given that the extension author does not distribute the bundle outside of the Visual Studio Marketplace, we are unable to include this in the `code-server` marketplace.

**Comment by cmoog** [comment]
Please reopen if these circumstances change. Thank you for the request!

**Comment by nhooyr** [comment]
Please upvote https://github.com/alefragnani/vscode-bookmarks/issues/260!

**Comment by gyzerok** [comment]
Done

**Comment by alefragnani** [comment]
I've just published the latest version (v11.4.0) on GitHub releases https://github.com/alefragnani/vscode-bookmarks/releases. Starting from now, every new release should be published as well.

Just to be clear, I didn't test the extension on code-server or any other VSCode alternative (VSCodium, Eclipse Theia, etc), so I don't know if/how it will work. I'm not sure how you (code-server) handles extension's compatibility on code-server, but feel free to open new issues, and we could talk about it.

Enjoy

**Comment by code-asher** [comment]
@alefragnani Thank you!

**Comment by oxy** [comment]
Added!
