### ISSUE TITLE
Add Project Manager Extension 

### ISSUE THREAD

**Issue by nathanrpage97** [cdr/code-server#1714]
- [ ] Extension name: Project Manager
- [ ] Extension GitHub or homepage: https://github.com/alefragnani/vscode-project-manager

**Comment by cmoog** [comment]
It appears that the core submodule of this repository is closed-source. Because of this, we are unable to build the .vsix. Given that the extension author does not distribute the bundle outside of the Visual Studio Marketplace, we are unable to include this in the code-server marketplace.

Please see this [issue](https://github.com/alefragnani/vscode-project-manager/issues/385).

**Comment by alefragnani** [comment]
I've just published the latest version (**v11.3.0**) on GitHub releases https://github.com/alefragnani/vscode-project-manager/releases. Starting from now, every new release should be published as well.

Just to be clear, I didn't test the extension on code-server or any other VSCode alternative (VSCodium, Eclipse Theia, etc), so I don't know if/how it will work. I'm not sure how you (code-server) handles extension's compatibility on code-server, but feel free to open new issues, and we could talk about it.

Enjoy

**Comment by nhooyr** [comment]
Awesome thank you @alefragnani
