### ISSUE TITLE
Context menu for "Paste" missing

### ISSUE THREAD

**Issue by dsyer** [cdr/code-server#1725]
This seems to be the case in every view/editor. You can use CTRL-C/CTRL-V to copy and paste, but the context menu (on right click) in an editor only has "Cut" and "Copy" and never "Paste", even if the clipboard should be full (after a "Copy" or a CTRL-C for instance).

**Comment by code-asher** [comment]
What browser are you using and are you accessing over https? `ctrl+v` performs a native paste in browsers but the context menu needs to use the clipboard API which is only available over https and isn't available in all browsers (Chrome supports it but Firefox doesn't for example).

Cut and copy still work in the context menu because there are workarounds that don't use the clipboard API but paste has no such workaround.

I think this is essentially https://github.com/cdr/code-server/issues/1106 but please correct me if it seems to be a different issue. 

I think the move will be to always show the paste option but when it's clicked display a message describing why it won't work and possible solutions (i.e. switch to Chrome).

**Comment by dsyer** [comment]
I don’t really know if that’s the same, but definitely related. I can’t get a TLS connection in this instance so that’s probably not going to be an option, but as long as I know something works I can work with that.
