### ISSUE TITLE
some resources are 404 (docker)

### ISSUE THREAD

**Issue by imba-tjd** [cdr/code-server#1759]
- Web Browser: FF 76
- Local OS: Win10 2004
- Remote OS: Debian bullseye
- Remote Architecture: amd64
- `code-server --version`: 3.4.0

![图片](https://user-images.githubusercontent.com/24759802/83590200-c7d4c700-a587-11ea-9346-4c2e480f1e23.png)

I run it by `docker run -it -p 9001:8080 -v "$PWD:/home/coder/project" -u "$(id -u):$(id -g)" codercom/code-server:latest` and access it by ip:9001, no proxy.

Some resources are 404, but it seems that I can enter the main page successfully? Don't know whether this is expected.

I saw https://github.com/cdr/code-server/issues/1642, but I'm using 3.4.0 and that issue seems to be fixed?

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by code-asher** [comment]
Those files are loaded when running a development build. They aren't needed in a production build because they're all bundled into a couple files.

I'm not sure why your browser is making requests for those files though. I ran the latest Docker image but I'm not seeing the same behavior. 

Have you ever ran the development build before? If so, maybe it's a caching issue. It would be worth a shot to use a private window and see if the same thing happens.

**Comment by nhooyr** [comment]
Yea as long as everything works you should be good!

Please feel free to comment if not and I'll ropen.

**Comment by imba-tjd** [comment]
Thanks. I can't reproduce this now, either :joy:

**Comment by nhooyr** [comment]
Awesome!
