### ISSUE TITLE
Unable to activate vscodevim.vim extension

### ISSUE THREAD

**Issue by peppy** [cdr/code-server#1799]
After a long delay on "activating extensions", the following error appears in worker extension how log:

```log
[2020-06-12 16:30:15.810] [exthost.log] [error] Activating extension vscodevim.vim failed due to an error:
[2020-06-12 16:30:15.813] [exthost.log] [error] {}
```

Running the server with `--log debug` only shows the following output:

```log
debug gzipping tar {"filePath":"/Users/dean/.local/share/code-server/extensions/vscodevim.vim-1.14.5"}
```

I have many other extensions loaded and working fine – seems to be specific to this one.

- Web Browser: Tested in chrome / safari / mobile safari
- Local OS: macOS / iPadOS
- Remote OS: macOS
- Remote Architecture: x64
- `code-server --version`:
```
info  Using config file ~/.config/code-server/config.yaml
3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
```

**Comment by code-asher** [comment]
Could you check the browser console for errors? I wonder if the tar.gz file is failing to load.

**Comment by peppy** [comment]
This does indeed seem to be the case:

```
Activating extension 'vscodevim.vim' failed: Failed to fetch.
_logMessageInConsole @ abstractExtensionService.ts:396
_logOrShowMessage @ abstractExtensionService.ts:410
$onExtensionActivationError @ mainThreadExtensionService.ts:70
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
a.onmessage @ webWorkerExtensionHostStarter.ts:70
````

Strangely enough, on the third refresh it did actually complete and activate on chrome.

On safari, not so much luck after many tries:

![image](https://user-images.githubusercontent.com/191335/84561935-67b20200-ad8b-11ea-84be-f1a3904c7dab.png)

Any further tips would be appreciated to try and track down the root cause.

**Comment by code-asher** [comment]
Safari and Firefox seem to be a lost cause for now since they don't support the regular expressions the Vim extension uses. I think Firefox will soon have support but I'm uncertain about Safari.

As for why the fetch is failing, it might help to check the network tab of the console and see if there's any extra information for the tar request, for example in the response section. It should look something like `/static/{commit}/tar?path=path to tar`. Maybe it would shed some light to copy that URL and browse to it directly and see if it downloads properly.

It's odd that it worked on the third attempt. The extension bundle is a decently large file, maybe there are some sporadic network issues of some kind? It's supposed to be cached so it doesn't have to fetch on subsequent loads but do you still see the issue after that successful load in Chrome?

**Comment by peppy** [comment]
Thanks for the explanations.

After multiple tests, I am no longer able to reproduce on chrome.. may have been network related. As safari was my main use case (on iPadOS) you are welcome to close this issue if it's out of the scope of this project.
