### ISSUE TITLE
Telemetry data

### ISSUE THREAD

**Issue by gmemstr** [cdr/code-server#1829]
I've noticed that the server makes a _lot_ of requests to `v1.telemetry.coder.com`. I'm curious what sort of data is being collected. It appears to be added here: https://github.com/cdr/code-server/blob/06b387fe98f93dceab989b4bdf1396c41035cb2a/ci/dev/vscode.patch#L2086 Is this simply redirecting data that Microsoft already collects in VSCode? I have Telemetry turned off in the settings, although I recognize that doesn't fully turn it off for VSCode either (at least, last I checked).

I'm flagging this as a bug, because I have telemetry turned off and the application should respect this setting. In the last 7 days my DNS server has blocked `40,871` requests to `v1.telemetry.coder.com`.

(edit) It occours to me that I don't have `--disable-telemetry` passed, but have disbled it in the settings instead. Curious if these are expected to behave the same.

- Web Browser: Firefox
- Local OS: Windows 10
- Remote OS: Arch Linux
- Remote Architecture: x64
- `code-server --version`: 
```
> ./code-server --version
3.4.0 69ad52907e8ea109345831d29da5425cb2a55047
```

**Comment by code-asher** [comment]
Yup it's the exact same data, we just fill in the telemetry endpoint with our own.

`--disable-telemetry` will create a telemetry handler that drops everything given to it so it should always work (it won't affect extension telemetry though since they use their own code for sending telemetry).

It looks like for some reason the configuration isn't being read or isn't being read properly. Even if the setting is false, it still reports it as being true. I don't see anything obviously wrong so we'll have to dig a bit.

**Comment by code-asher** [comment]
Thanks for reporting this! Broken configuration is a pretty big deal. I'll need to pay attention to how VS Code registers services when updating in the future so I don't miss changes in how things are initialized like this again.
