### ISSUE TITLE
Paste image into editor

### ISSUE THREAD

**Issue by jet10000** [cdr/code-server#1849]
I wanto to use code-server for edit my blog markdown file, how to paste image into editor from clipboard?

**Comment by code-asher** [comment]
Thanks for the feature request! VS Code itself doesn't seem to support so it might be better to raise this upstream (https://github.com/microsoft/vscode) unless we want to add support for it ourselves.

There is a paste image extension but it won't work since it's not designed for use in the web (that would need to be fixed in the extension itself).

The only workaround I can think of is to save the image locally then upload it (for example with drag and drop over the editor or with something like `scp`) then link to it from the markdown file.

**Comment by nhooyr** [comment]
Yea this is best handled by the VS Code team!

**Comment by nhooyr** [comment]
Also see #1819

**Comment by predkambrij** [comment]
Is there an open issue in https://github.com/microsoft/vscode ?

**Comment by jsjoeio** [comment]
There might be - you're welcome to look and link back here
