### ISSUE TITLE
code-server update fails on digital ocean droplet

### ISSUE THREAD

**Issue by rholland** [cdr/code-server#1852]
I am running the one-click code-server on digital ocean and get update failed when prompted to update to 3.4.1.  Here is the version response after closing all browser tabs and rebooting the computer.

`coder@rivetcalc-server01:~$ code-server --version
info  code-server 3.0.2 e480f6527e11344a7c69b7cd024bce9379cea7f0
error listen EADDRINUSE: address already in use 0.0.0.0:443
coder@rivetcalc-server01:~$ `

Can you tell me why I get this conflict and how to get the update to work? Thanks.

**Comment by code-asher** [comment]
I'm not super familiar with the Digital Ocean droplet unfortunately but something must already be running on port 443, probably code-server? `ss -lpn | grep 443` should tell you, although you'll need to run it as root.

It might be that the update failed because it doesn't have permissions to overwrite the current code-server. I'm not sure how we run code-server on the droplet but it might be sufficient to `chown` the code-server directory.

**Comment by nhooyr** [comment]
See #1654
