### ISSUE TITLE
Terminal stuck in Starting...

### ISSUE THREAD

**Issue by rohinrohin** [cdr/code-server#1888]
Hi

A couple of our users have reported issues when they're on flaky networks in India (ping packet loss 5-10%) that the terminal is stuck in "Starting...". 

Is there anything that can be done for code-server to work in these conditions?

Thanks!

- Web Browser: Chrome
- Local OS: Windows/Linux/Mac
- Remote OS: Ubuntu 18.04
- Remote Architecture: Kubernetes via Nginx
- `code-server --version`: 3.4.1

**Comment by nhooyr** [comment]
Is it stuck or does it eventually work?

**Comment by Crazykado-iphone8MacProOs** [comment]
Echo on start terminal / Sudo.start.term

**Comment by GouravSardana** [comment]
@nhooyr Its's stuck until packet loss <5%

**Comment by lights0123** [comment]
I'm experiencing this locally in a Docker container. I was getting the error `open '/proc/0/status': Error: ENOENT: no such file or directory, open '/proc/0/status'` when creating a new terminal window, but I believe that was because I didn't have zsh installed in my container. After doing so, the terminal is still "Starting...", and no log output occurs.

**Comment by alan-he** [comment]
When client network is slow, The "teminal" was stuck at "starting".  And in the meantime, "OUTPUT" [Log(Window)] showed :
**[error] EACCES: permission denied, open '/proc/1/environ'**
And I found, there were 4 processes. (normally, when working good, there are only 2 processes)
4170  0.0  0.3 1394380 119532 ?      Sl   14:21   0:00 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/opt/plugin/code-server/lib/vscode/out/vs/server/node/uriTransformer
4379  0.0  0.0 859388 23044 ?        Sl   14:21   0:00 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=watcherService
10254  1.2  0.3 1394380 119532 ?      Sl   14:21   0:38 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/opt/plugin/code-server/lib/vscode/out/vs/server/node/uriTransformer
10265  0.0  0.0 859388 23044 ?        Sl   14:21   0:00 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=watcherService

**Comment by alan-he** [comment]
> When client network is slow, The "teminal" was stuck at "starting". And in the meantime, "OUTPUT" [Log(Window)] showed :
> **[error] EACCES: permission denied, open '/proc/1/environ'**
> And I found, there were 4 processes. (normally, when working good, there are only 2 processes)
> 4170 0.0 0.3 1394380 119532 ? Sl 14:21 0:00 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/opt/plugin/code-server/lib/vscode/out/vs/server/node/uriTransformer
> 4379 0.0 0.0 859388 23044 ? Sl 14:21 0:00 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=watcherService
> 10254 1.2 0.3 1394380 119532 ? Sl 14:21 0:38 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/opt/plugin/code-server/lib/vscode/out/vs/server/node/uriTransformer
> 10265 0.0 0.0 859388 23044 ? Sl 14:21 0:00 /opt/plugin/code-server/node /opt/plugin/code-server/lib/vscode/out/bootstrap-fork --type=watcherService

"terminal.integrated.inheritEnv": true solve the problem. Somehow, when opening the codeserver page, "terminal.integrated.inheritEnv" option is unchecked, and caused terminal stucked in starting

**Comment by nhooyr** [comment]
Interesting. 🤔

**Comment by XciD** [comment]
I've the same issue, can start a terminal and nothing appear on logs.
Using docker with:
```
docker run -it  -u "$(id -u):$(id -g)"  codercom/code-server:latest

**Comment by louchenyao** [comment]
Same problem. But the packet loss rate seems ok.

**Comment by mabunixda** [comment]
We are having the same issues but also not reproducable, because we can use the same code-server by 2 users and one of them is having a problem by the stuck starting terminal, and the other user is able to open a terminal. 

Today we were able to solve the issue for both users by clearing the cache of the VM by
```
echo 1 > /proc/sys/vm/drop_caches
```

We run the code-server as systemd-service on ec2 t3.medium instances with caddy and letsencrypt.
We are running this setup for trainings with about 10 participants. But we are also not aware why this happens, because it appears on 1 or 2 of 10 instances and not on each of them. And the setup is created by terraform so this should be identical ( hopefully ) 

A restart of code-server does not fix the problem ...

**Comment by mabunixda** [comment]
Today we ran into this situation again ... the situation was fixed by disabling selinux. But i am not able to say that this is/was the root cause of the problem

**Comment by mabunixda** [comment]
Again i was experiencing the terminal problem - this time prometheus and a nodeexporter was also running on the installation. 
The VM was initially checked and terminal opened, then after 2 days of idle state code-server was used again and the terminal problem appeared again. After a few minutes the problem was not present anymore.
About 5 hours later the problem appeared again on this specific VM.
During this 3 days 8 VMs providing code-server were running. None of them showed this specific problem in this period except a single installation.

The only metric which is noticeable is the memory page faults:
![1st appearance](https://user-images.githubusercontent.com/1193145/99635786-c79b8b80-2a42-11eb-88b4-be01323d174a.png)
![2nd appearance](https://user-images.githubusercontent.com/1193145/99635775-c5d1c800-2a42-11eb-9470-018c9e0311be.png)

**Comment by caio-vinicius** [comment]
That's unfortunately annoying. Happening all the time

**Comment by shuivin** [comment]
# share the method i resolve the bug:

step1. delete the file:
~/.local/share/code-server/User/settings.json

Done.

**Comment by kavinvin** [comment]
In my case, I found that this problem is due to using linux service file without specifying working directory. So I guess it got some permission problem. After I specified `WorkingDirectory` for the service, the problem was resolved.

```
[Unit]
Description=code-server
After=network.target

[Service]
Type=exec
ExecStart=/usr/bin/code-server
Restart=always
User=%i
WorkingDirectory=/home/%i

[Install]
WantedBy=default.target
```
