### ISSUE TITLE
Modify code server subpath

### ISSUE THREAD

**Issue by KMFtcy** [cdr/code-server#1987]
I would like to access code server with a base url, which may be satisfied with sub-path mentioned in FAQ. However this path can not be changed with any argument, like NotebookApp.base_url in jupyter launching command or path_prefix in tensorBoard launching command. 
Can this feature be updated?

**Comment by code-asher** [comment]
code-server should work no matter what base you put it behind so there should be no need for such a setting. Is there a problem you're running into?

**Comment by code-asher** [comment]
Oh, are you running code-server without a reverse proxy? To run code-server behind a base path you'll need to run a reverse proxy like Caddy.

**Comment by RowdyHowell** [comment]
I think he's referring to something like the `--base-path` that exists in version 2.  Is that possible in version 3?

**Comment by code-asher** [comment]
Nope, code-server should be base path agnostic which is why the flag was removed. We rely on reverse proxies to serve code-server at a base path (actually that was always the case, `--base-path` was only ever used to redirect from the login page to the root but now we just do it relatively by redirecting to `../`).

**Comment by mklechan** [comment]
@code-asher  I think code-server needs to be aware of the base-url path, because behind my reverse proxy vscode is making requests for js/css files with incorrect urls. For example code-server is running at https://servername/vscode 
 and is making requests for https://servername/static/xxx/code-server/lib/vscode/out/vs/workbench/workbenc.web.api.css
instead of https://servername/**vscode**/static/....

Or is my reverse proxy just not configured properly...

**Comment by eryx** [comment]
+1 

I also need this feature that allowed multi users to access the multi code-server instances in the same domain and different base-path:

https://example.com/user-a/   proxy to 10.0.0.1:8080/user-a/

https://example.com/user-b/   proxy to 10.0.0.2:8080/user-b/

**Comment by code-asher** [comment]
@eryx The recommended way to do that is to use a reverse proxy like Caddy or NGINX. 

I'll close this issue for now since I don't think we plan on adding a base path flag to code-server. If there are cases that can't be handled with a reverse proxy let me know though!
