### ISSUE TITLE
Microsoft  Remote Development Extension Pack 

### ISSUE THREAD

**Issue by bwired-nl** [cdr/code-server#2017]
Details on the code-server extension marketplace are at

https://github.com/cdr/code-server/blob/master/doc/FAQ.md#whats-the-deal-with-extensions
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

Please fill in the issue template!
**not able to select and install this extensions**
can these 2 be added?
- [ ] Extension name:
Remote Development Extension Pack
Remote - SSH
- [ ] Extension GitHub or homepage:
https://github.com/Microsoft/vscode-remote-release
https://github.com/Microsoft/vscode-remote-release

**Comment by code-asher** [comment]
Unfortunately we can't include these because of licensing issues. See https://github.com/cdr/code-server/blob/v3.4.1/doc/FAQ.md#differences-compared-to-vs-code

We'd like to re-implement these as open source extensions but there's no timeline on that. See https://github.com/cdr/code-server/issues/1315
