### ISSUE TITLE
Error loading webview: Service Workers are not enabled in browser. Webviews will not work.

### ISSUE THREAD

**Issue by codeoflin** [cdr/code-server#2038]
![image](https://user-images.githubusercontent.com/45932283/91788102-f07b6400-ec3d-11ea-89f9-69f67c46dff2.png)
when I want to install a extension i just got this:
Error loading webview: Service Workers are not enabled in browser. Webviews will not work.

**Comment by pavlelee** [comment]
@codeoflin https://developer.mozilla.org/zh-CN/docs/Web/API/Service_Worker_API/Using_Service_Workers
must https

**Comment by codeoflin** [comment]
> 
> 
> @codeoflin https://developer.mozilla.org/zh-CN/docs/Web/API/Service_Worker_API/Using_Service_Workers
> must https

Thanks

**Comment by cheulyop** [comment]
Wait, I have the same issue and wasn't able to find how you can fix it in the linked document. @pavlelee @codeoflin Can you explain a bit more about how you resolved this issue?

**Comment by code-asher** [comment]
https://github.com/cdr/code-server/blob/v3.5.0/doc/guide.md#lets-encrypt may be of use. Caddy is a pretty painless way to get HTTPS going assuming you have a domain name.

**Comment by tsgiannis** [comment]
Hello , may i ask for clarification
I am running code-server from my VPS (Ubuntu/1gb) and i get this message.
I run it like this http://mysite.com:9999
if i switch to 
https://mysite.com:9999 will extensions work and for example have .net core extensions running so i can debug and run .net core applications

**Comment by Haseb-ali** [comment]
I am also facing these issues I tried my best but issues still here

**Comment by code-asher** [comment]
@Haseb-ali Please feel free to open a new issue and we can try to debug.

Also if possible you could try `--link` which will proxy through our cloud and handle TLS for you.

**Comment by demetrius2017** [comment]
Please switch off add block in your browser, if you are coding by GitHub Codespaces

**Comment by GrantRVD** [comment]
I was attempting to use GitHub Codespaces to edit some Jupyter notebooks, because I don't have a local environment setup on my computer. Using Firefox, I was encountering this error, even after disabling all my adblockers and anti-tracking extensions. What ultimately solved the issue for me is disabling this new feature in Firefox meant to stop inter-site tracking. Other browsers may have similar features, so if anyone else is having issues with webview, try disabling features like Total Cookie Protection. The screenshot below is off the checkbox I unticked to make Codespaces work.
![image](https://user-images.githubusercontent.com/4311681/170824109-7ce210a3-cd8a-488d-bbed-2bfc5f2f6b26.png)

**Comment by MdShafiurRahman0** [comment]
> Please switch off ad block in your browser, if you are coding by GitHub Codespaces

Thank you, it has solved my issue.
