### ISSUE TITLE
client looses connection with server (partly)

### ISSUE THREAD

**Issue by sharypovandrey** [cdr/code-server#2063]
Hello,

- Web Browser:
Mozilla Firefox 80.0.1 (64-bit)
- Local OS:
Ubuntu 16.04
- Remote OS:
Ubuntu 16.04
- Remote Architecture:
docker image codercom/code-server:latest

I launched code-server container on Kubernetes.
I opens vscode tab in the browser, wait few seconds, try to create new file (or edit existing), check current directory using `ls` and found nothing.
I see that websocket has send data regarding new file. 

![image](https://user-images.githubusercontent.com/13822439/92296840-216fd780-ef63-11ea-90b1-237eb459f16c.png)

**Comment by Leletir** [comment]
Hi, since I have updated Firefox to 80.0.1 I have this error on code-server and noVNC:
"Error: WebSocket close with status code 1006 on remoteAuthorityResolver.ts:69:2"

I don't know yet if it's on Firefox side, do you have more infromations ?

**Comment by code-asher** [comment]
@sharypovandrey Are you able to replicate this by running Docker locally? I tried with the latest image (3.5.0) and Firefox 80 but when I right click > new file the file immediately appears on the file system and is shown by `ls`.

@Leletir I recommend opening a new issue since it seems unrelated to this one. That said, you shouldn't need to use noVNC with code-server, right? You can just browse to code-server directly.

**Comment by Leletir** [comment]
Hi,

I've been able to reproduce this error on several products, jupyterlab, novnc, and code server(@code-asher sorry I've not been clear about this in my previous image, I'm not running code-server inside novnc), so I think it's on Firefox side, everything works with Chromium

**Comment by code-asher** [comment]
Ohhh I see. I haven't been able to reproduce any websocket errors on Firefox. Are you connecting to them directly or through some kind of proxy?

**Comment by sharypovandrey** [comment]
@code-asher when I run docker locally everything works like a charm. Could be the issue related to SSL certificate?

**Comment by code-asher** [comment]
Hmm I'm not sure but it seems unlikely since it's at least partly working, for example you're getting the file tree contents. You said you weren't able to edit existing files either? Does the content load at all? What about the search panel? And are you able to install extensions?

It might be worth turning on debug logging and checking out the logs: https://github.com/cdr/code-server/blob/v3.5.0/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by geiseri** [comment]
I am running behind trafik and I see something similar, but what is strange is in chrome is just "stops."  No errors, it just that messages stop on the websocket, and I need to reload the window for it to respond.  I will see if I can get more information, trace didn't show anything obvious.

**Comment by geiseri** [comment]
I might have found something.  I was looking through the HAR dump of the last one and I found this:
![image](https://user-images.githubusercontent.com/2265693/95641356-c48aa400-0a6f-11eb-92e6-aeb4023cf6f3.png)
It starts to loop here, what is interesting is that I am connected over SSL but the reconnect is happening on port 80.  I see this until I do a reload.   I apologize for the massive HAR file, but of course as I am watching it took its own sweet time and I didn't catch it right away.  What is also interesting is that I can still save the files on the server, but things like linters won't run.  I will see if I can whittle this down, but it almost looks like it is trying to connect to port 80 explicitly. 

[logs.tar.gz](https://github.com/cdr/code-server/files/5358187/logs.tar.gz)
[coder-logs.tar.gz](https://github.com/cdr/code-server/files/5358188/coder-logs.tar.gz)
[code.house.geekcentral.io.har.gz](https://github.com/cdr/code-server/files/5358189/code.house.geekcentral.io.har.gz)

**Comment by code-asher** [comment]
Ah the log that reports 80 is actually wrong. We patch VS Code to use
the correct port rather than 80 but don't actually change the port
number it's passing around. We should rework that so we change the port
at its source instead (it was easier this way since we had to change
other things as well, like to use wss instead of ws, but definitely a
bad move since it causes confusing logs like this).

**Comment by code-asher** [comment]
Although maybe that 80 is being used elsewhere and causing a problem. If
so they would show up in the network tab.

**Comment by geiseri** [comment]
Yeah, I didn't see it connect.  Or even attempt for that matter, but I am thinking that something might be happening around that time.  I was going to sift through it a bit more tonight.  I seem to hit it quite a bit when I am using the terminal, but seeing that it is not giving me any network connection error I am wondering if something is causing it to "reconnect" but still wait for messages to come back on the old socket.

**Comment by nhooyr** [comment]
Has anyone been able to reproduce this on latest releases?
