### ISSUE TITLE
keybindings.json doesn't take effect till reloading

### ISSUE THREAD

**Issue by hyw208** [cdr/code-server#2279]
I created a docker image with ~/.local/share/code-server/keybindings.json pre-populated to get around F10 used for menubar focus which conflicts with F10 debug: step over for python. The keybindings.json is as follow
[
  {
    "key": "f10",
    "command": "-workbench.actions.menubar.focus"
  }
]

However it doesn't work till I bring up keybindings.json (with command palette -> Preferences: Open Keyboard Shortcuts (JSON)), which is interestingly empty even though I provided the file under the same path. Then I have to copy the content above and save this keybindings.json brought up by command palette. Then it will start working. The trouble is that I have to do it every time I restart the docker instance. 

There was a closed issue "150" below but it's still not fixed for linux 
https://github.com/cdr/code-server/issues/150

- Web Browser: Chrome
- Local OS: Window 10
- Remote OS: Redhat 7
- Remote Architecture: AMD
- `code-server --version`: 3.6.1

**Comment by code-asher** [comment]
I wonder if this is the same problem that is causing issues with
settings: https://github.com/cdr/code-server/issues/2274

**Comment by cfal** [comment]
It seems like since 3.6.1 and higher, only the keybindings.json stored in local storage is considered, and ~/.local/share/code-server/User/keybindings.json is completely unused. Unlike ~/.local/share/code-server/User/settings.json, which still work but can be overridden by the settings.json in local storage, there's no such concept as "Remote" keybindings. The only solution I found was to copy the keybindings to each browser and make sure I never clear data, or downgrade to 3.6.0.

**Comment by hyw208** [comment]
I tested 3.6.0 and it has exactly the same issue as 3.6.1 unfortunately...

**Comment by nhooyr** [comment]
Will be in `v3.7.3` which I'll get out today!
