### ISSUE TITLE
Compute requirements for code-server

### ISSUE THREAD

**Issue by jgbradley1** [cdr/code-server#232]
Can general guidance be provided somewhere in the README on the recommended minimum compute requirements are for code-server to function correctly?

This will help people who are interested in self-hosting. There are some memory/cpu [issues](https://github.com/codercom/code-server/issues/132) right now that have to be accounted for. I'm also wondering how it compares to the desktop VS Code [requirements](https://code.visualstudio.com/docs/supporting/requirements).

**Comment by sr229** [comment]
You need at least 2GB of RAM to run Coder and a CPU that is 64 bit, and is x86_64. The reason why 2GB is required because the server eats at least 1-1.4GB in average

**Comment by wcypierre** [comment]
@sr229  I've allocated 4gb of ram and ran it on a folder with no files under it and it still doesn't work though

**Comment by sr229** [comment]
It does not relate to your specs, I need your system info and diagnostic logs @wcypierre

**Comment by wcypierre** [comment]
@sr229  where can I extract the logs from?

**Comment by sr229** [comment]
if you launch the binary manually, the log output is in stdout. If by SystemD, use journalctl

**Comment by SuperSandro2000** [comment]
![](https://i.imgur.com/R9d4VfA.png)
Around this on idle. Can't explain the jitter.

**Comment by ruslanguns** [comment]
I created a dropplet 5$ for testing coder and got an issue that breaks since the buffer: 

```bash
root@ruso:~# code
(node:1255) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server v1.903-vsc1.33.1
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/root/.local/share/code-server","extensions-dir":"/root/.local/share/code-server/extensions","working-dir":"/root","log-dir":"/root/.cache/code-server/logs/20190421115346166"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
INFO
INFO  Password: 44a8e1776f389e43792aec9b
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO
INFO  Starting shared process [1/5]...
WARN  stderr {"data":"(node:1279) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
INFO  WebSocket opened / {"client":1,"ip":"47.63.161.195"}
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn [as _spawn] (child_process.js:538:9)
    at t.async (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34598)
    at e.exports (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34099)
    at e (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:32722)
    at Timeout.u [as _onTimeout] (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:33015)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

```

![image](https://user-images.githubusercontent.com/19806968/56469694-e6840700-6434-11e9-84d0-b1e50c34ac18.png)

Something is wrong...

**Comment by sr229** [comment]
It's not a bug according to the stack trace, `code-server` once has a running interactive session in the browser will begin to spike on RAM usage to 1GB (RIP Raspberry Pi users)

**Comment by ruslanguns** [comment]
Also RIP to low budget users for DO Droplets lol. 

Thanks for response it is good to know.

**Comment by bensonokiora** [comment]
Am getting the same error with a new 2GB Ram Droplet 
`root@ubuntu-s-code-server:~/code-server1.903-vsc1.33.1-linux-x64# ./code-server                                                                                                               -p 8080
(node:1797) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security                                                                                                              and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or B                                                                                                             uffer.from() methods instead.
INFO  code-server v1.903-vsc1.33.1
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/root/.local/share/code-server","extensions-dir"                                                                                                             :"/root/.local/share/code-server/extensions","working-dir":"/root/code-server1.9                                                                                                             03-vsc1.33.1-linux-x64","log-dir":"/root/.cache/code-server/logs/201904221120119                                                                                                             25"}
INFO  Starting webserver... {"host":"0.0.0.0","port":"8080"}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://github.com/codercom/code-ser                                                                                                             ver/blob/master/doc/security/ssl.md
INFO
INFO  Password: dc79e9202c09eac4aee225e7
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:8080/
INFO
INFO  Starting shared process [1/5]...
WARN  stderr {"data":"(node:1809) [DEP0005] DeprecationWarning: Buffer() is depr                                                                                                             ecated due to security and usability issues. Please use the Buffer.alloc(), Buff                                                                                                             er.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
`

**Comment by sr229** [comment]
@bensonokiora I don't think this relates to this issue at all.

**Comment by sr229** [comment]
@ruslanguns there is a way to run it on a 1GB environment

Swapping is a marvelous ad dangerous way to extend the lifespan of your server

**Comment by ruslanguns** [comment]
I ll check that... thanks! 👍

**Comment by code-asher** [comment]
v2 requirements should be lower than v1 and are document here: https://github.com/cdr/code-server#requirements
