### ISSUE TITLE
Markdown previews not working

### ISSUE THREAD

**Issue by ctlajoie** [cdr/code-server#2329]
When I try to open a preview on a markdown file I get `command 'markdown.showPreviewToSide' not found`

I am not sure if it is relevant to this issue but I am also experiencing #1593, which was an issue I reported a while back. It had been fixed (known to be working in 3.4.1) but appears to have returned in recent builds and that issue was reopened.

- Web Browser: Chrome
- Local OS: Linux
- Remote OS: Linux
- Remote Architecture: x86_64
- `code-server --version`: 3.7.1 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34

**Comment by code-asher** [comment]
The markdown extension linked in that issue is still broken I believe, I
think it isn't being built correctly in our marketplace so we'll need to
take a look and see why.

The built-in markdown preview should work though. I just tried with
3.7.1 and Chrome (via right-click > open preview on the markdown file
tab) and it worked for me.

Are there any other errors in the browser console?

In my case even though the markdown preview is showing I'm still getting
a bunch of errors on the webview endpoint; that might be related.

**Comment by ctlajoie** [comment]
I was able to get preview to load up after I updated chrome, which was several months out of date... my bad. I did run into those 404s though. Looks like you already have a PR for that.
