### ISSUE TITLE
Add file and directory download feature

### ISSUE THREAD

**Issue by jgbradley1** [cdr/code-server#233]
There should be a file/folder download option, either in the File menu or the right-click menu so users can pull files out of the image.

A similar request for a file upload option was made [here](https://github.com/codercom/code-server/issues/31).

These two features are a nonstarter before I can choose to use code-server over Theia.

**Comment by nol166** [comment]
This would be super cool. I believe this is on our roadmap but there are some higher priority issues to take care of first.

**Comment by deansheather** [comment]
If we add download/upload right click context menu buttons, one feature we could add is dragging and dropping files from code-server to your desktop, which is [possible](https://www.thecssninja.com/javascript/gmail-dragout) apparently.

**Comment by achirkin** [comment]
Hi, I have an issue with uploading files feature, but I was redirected here from #31 . It looks like the upload feature is not cross-platform enough.
I am hosting code-server on linux;

  * Drag-n-drop on a linux machine works like a charm
  * On chrome OS it says "Cannot read property 'isFile' of null"
  * On windows it tries to copy a file into a path with backslashes instead of normal slashes. I get something like "Cannot copy '/\home\username\bluh-bluh': access denied"

In all three cases I was using chrome on the client side.

**Comment by sr229** [comment]
This is sadly a upstream issue. Please bring this up on Microsoft/vscode since it concerns them as well. I'll be closing this off now.
