### ISSUE TITLE
FreeBSD 11.3-RELEASE-p14 install script throws errors

### ISSUE THREAD

**Issue by irgipaulius** [cdr/code-server#2349]
- Web Browser: not applicable
- Local OS: not applicable
- Remote OS: FreeBSD 11.3-RELEASE-p14. (a jail inside a FreeNas server)
- Remote Architecture: x86
- `code-server --version`: 3.7.2 a0db6723c1ef22b40d7ac0df5ac1bb9a92e4fe46

<hr />

Problem with: installation script

<hr />
## How to replicate

1. create a new jail in FreeNas. SSH into it with sudo permissions
2. `pkg upgrade`
3. `curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run`
  3.1. it finishes successfully, everything seems fine
4. `curl -fsSL https://code-server.dev/install.sh | sh`
  4.1 installs `code-server` successfully
  4.2 but it spews discouraging errors
  4.3 and does not print out info on how to run and start using code-server after it's finished, like it's supposed to do according to the [documentation](https://github.com/cdr/code-server/blob/v3.7.2/doc/install.md#installsh).

<hr />

Logs go into what seems like an endless loop of these 12 error lines over and over again:
```
Done in 0.07s.
extensions/xml: installing dependencies
yarn install v1.22.10
warning ../package.json: No license field
info No lockfile found.
[1/5] Validating package.json...
warning xml@1.0.0: The engine "vscode" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 0.07s.
```

And upon scrolling a bit higher, you can see this error:

![image](https://user-images.githubusercontent.com/20173109/99888207-05bfc780-2c5c-11eb-95a0-fb22800227ba.png)

<hr />

## Consequences
It does not influence my accessibility to the product, but it did influence the **experience** of the installation process. I panicked that something is wrong with my system and I started debugging until 20 minutes later I had an idea to run `code-server --version` and it proved that it installed successfully. Wasted time I'm not getting back.

**Comment by code-asher** [comment]
Thank you for reporting. VS Code uses rimraf in their post-install to
remove some files from some Node modules although I'm not entirely sure
why as it still works without doing that.

I'm not sure how rimraf is missing though; it should be in the
package.json dependencies. I have sometimes seen dependency downloads
time out and instead of erroring yarn/npm seem to just keep chugging
along which results in problems later when those dependencies are used
(it happens in our CI fairly often).

You're able to use code-server though? Including the terminal,
extensions, etc?

I'll take a look at 3.7.2 and see if I can reproduce.

**Comment by irgipaulius** [comment]
I don't yet have the possibility of doing that since I did not enable port forwarding on my remote server, lol. I was just able to install as a preparation for when I actually will be home and connect to my FreeNAS machine via WAN. So I guess I Can't answer you now.
