### ISSUE TITLE
proxy not work for post

### ISSUE THREAD

**Issue by snadn** [cdr/code-server#2377]
POST request body is not proxied to the servers. Maybe the same problem as https://github.com/chimurai/http-proxy-middleware/issues/40

- Web Browser: chrome 86
- Local OS: macOS 10.13
- Remote OS: docker
- `code-server --version`:  3.7.4

1. start a server in code-server terminal
2. post to server without header 'application/json' by proxy, the server receive body
3. post to server with header 'application/json' by proxy, the server can not receive body

**Comment by nhooyr** [comment]
Please fill in the issue template!

And make sure you're authed to the proxy.

And see https://github.com/cdr/code-server/issues/2128

**Comment by snadn** [comment]
@nhooyr 
I have added the steps to reproduce the problem in the issue, and I start code-server with config `auth: none`

**Comment by nhooyr** [comment]
@snadn There is no header `application/json`. Are you referring to `Accept` or `Content-Type`?

**Comment by snadn** [comment]
@nhooyr I mean `Content-Type`

**Comment by Inlustra** [comment]
@snadn I'm seeing the same issues as you.
Server never receives the post and instead just hangs forever.

(Until I get a 502, Socket hang up)

**Comment by scumbug** [comment]
Running an express server and have the same issue trying to get POST request body of types `application/json` and `application/x-www-form-urlencoded` (Just hangs until I kill the server or 502 after awhile)

Tried both `body-parser` and `express.json()`/`express.urlencoded` with no success

`multipart/form-data` works fine using `multer` to parse the data

**Comment by BenBJD** [comment]
I have the same problem with a Flask server.

Going local to port 5000 on my server it works perfectly, but proxying through code-server by http://code.domain.co.uk/proxy/5000/user/login causes curl and flask to hang until I ctrl-c. The same happens if i access code-server locally by port 8443. I used the network tab of Firefox dev tools to send a request with more control, and instead of a hang I just got a 400 bad request.

Using a breakpoint I found it was on the first line in the route which was `user = request.form["user"]` that was hanging, which means the value user must not be in the body of the POST request. So it seems pretty obvious for some reason the POST body isn't getting through the code-server proxy to flask. If it matters, I am running code server through an nginx reverse proxy along the lines of [this](https://github.com/linuxserver/reverse-proxy-confs/blob/master/code-server.subdomain.conf.sample) with an extra few lines for a custom font.

**Comment by Inlustra** [comment]
@snadn Do you need more info that what has been posted?

**Comment by BenBJD** [comment]
I managed to fix the issue (I think) but the yarn watch thing gives me a `[tsc] src/node/routes/pathProxy.ts:38:13 - error TS2339: Property 'body' does not exist on type 'IncomingMessage'.` for the 3 times i used `req.body`. It did seem to receive the body when i tested it with a simple express server despite this. I only did it for the subfolder proxies for now because they were easier to test and I had to learn what express is to do this so it might not be perfect

My edited src/node/routes/pathProxy.ts is [here](https://github.com/BenBJD/code-server/blob/master/src/node/routes/pathProxy.ts)

**Comment by lhaley2011** [comment]
If it is helpful, I use linuxserver's builds of code-server. It looks like the proxy issue started between versions 3.6.2 and 3.7.4. Build 3.6.2 will work if you roll back to it.

**Comment by nhooyr** [comment]
Confirmed this, working on a fix!

Also added a test to prevent any future breakage in this area!

**Comment by nhooyr** [comment]
Fix is at https://github.com/cdr/code-server/pull/2609
