### ISSUE TITLE
Release to AppImage 

### ISSUE THREAD

**Issue by Phelexand** [cdr/code-server#2387]
Such as vscodium , a target of glibc2.16-x86_64.AppImage  wants to be released.

**Comment by nhooyr** [comment]
What's the advantage of AppImage over Docker?

**Comment by oxy** [comment]
To me, the major benefit of a `.AppImage` is that they're self-contained and usually automatically managed by the distro - and that they also don't use a container and just run directly on the host.

With AppImages, any Linux distro could simply download a file, `chmod +x` and then run it, and it should in theory work with no extra dependencies, with the entire app contained into one file.

**Comment by yamsjix** [comment]
What's more, my environment  is under linux kernel 2.6.32。 Docker works on higher.

**Comment by supriyo-biswas** [comment]
Appimage requires FUSE, which is not commonly installed on servers and negates the potential advantages.
Also for those on 2.6.x kernels -- you're likely running on an OpenVZ kernel, which doesn't support FUSE.

**Comment by nhooyr** [comment]
Closing as there isn't enough benefit to AppImage to justify adding it to the releases. The binary releases only have a minimum glibc of v2.17 which is nearly 8 years old now. The benefit/adoption of AppImage seems to be around desktop applications as well where users are used to downloading applications via the browser instead of a package manager.

**Comment by nhooyr** [comment]
Also like @supriyo-biswas mentioned it requires FUSE.

Finally, you can always use the npm package if you need to install on such old distributions. See https://github.com/cdr/code-server/blob/master/doc/install.md#yarn-npm
