### ISSUE TITLE
Settings sync: cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by neighthan** [cdr/code-server#240]
- `code-server` version: v1.32.0-245
- OS Version: Ubuntu 16.04
- Extension: [settings sync]

## Description

After I installed settings sync, I tried to set it up like normal with my GitHub token using the "Sync: Update / Upload Settings" command (shift-alt-u). I get

```
Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
```

Looking at the console shows

```
[Extension Host] TypeError: Cannot read property 'token' of undefined	at d.<anonymous> (/cluster/nhunt/.local/share/code-server/extensions/shan.code-settings-sync-3.2.7/out/extension.js:7:47337)	at Generator.next (<anonymous>)	at s (/cluster/nhunt/.local/share/code-server/extensions/shan.code-settings-sync-3.2.7/out/extension.js:7:43848)	at <anonymous> (at Function.LogException (/cluster/nhunt/.local/share/code-server/extensions/shan.code-settings-sync-3.2.7/out/extension.js:7:44292))
```

It seemed like some others have gotten settings sync to work - was there any different setup for code-server than for normal VS Code?

## Steps to Reproduce

1. Install the settings sync extension
2. Run the update / upload settings command.

[settings sync]: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by neighthan** [comment]
This was apparently because I didn't have the folder `~/.config/Code/User` where the GitHub token, etc. for this extension are stored. I think this is still a bug - code server should be able to create that directory if it is needed and doesn't exist. When I created the directory myself and reloaded, I was able to enter my token without an error.

**Comment by neighthan** [comment]
Perhaps it should also be using the `~/.local/share/code-server/User` folder instead?

**Comment by nanyang24** [comment]
Hello~ @neighthan 
I have the same problem with you.
So, What is your final solution?

**Comment by neighthan** [comment]
I created the directory `~/.config/Code/User` because I saw earlier error messages (before I tried to upload settings) related to not finding a file there. This did get rid of the error and allowed me to upload my current settings to a gist.

However (this is a different issue), I was not able to use settings sync to sync extensions. This is a known issue and might not be able to be resolved - it has to do with MS extensions not all being open source / no API to download even those extensions that are, so code-server has their own subset of extensions they build from git repos which you can install.

Because of the extensions error, I didn't end up looking into whether I could sync everything else from a gist; I'm concerned there might be problems there as well because of the different path used by code-server, but I haven't tested this.

**Comment by nanyang24** [comment]
@neighthan 
Thank you for your patient reply.
Our solution is very similar to the first one.
But there is nothing I can do about the second question.
Let's look forward to the future

**Comment by guyuxiang** [comment]
> I created the directory `~/.config/Code/User` because I saw earlier error messages (before I tried to upload settings) related to not finding a file there. This did get rid of the error and allowed me to upload my current settings to a gist.
> 
> However (this is a different issue), I was not able to use settings sync to sync extensions. This is a known issue and might not be able to be resolved - it has to do with MS extensions not all being open source / no API to download even those extensions that are, so code-server has their own subset of extensions they build from git repos which you can install.
> 
> Because of the extensions error, I didn't end up looking into whether I could sync everything else from a gist; I'm concerned there might be problems there as well because of the different path used by code-server, but I haven't tested this.

I have the same issue. The above solution does not work for me. 
I still get the same error: Sync : `Error Logged In Console (Help menu > Toggle Developer Tools).`

**Comment by foresthoffman** [comment]
@neighthan You're correct, the Settings Sync extension should be looking at `~/.local/share/code-server/User` rather than `~/.config/Code/User` for linux.

From the Settings Sync [README](https://github.com/shanalikhan/code-settings-sync#global-settings):
> Global settings are present in syncLocalSettings.json inside User folder. These settings will be shared across multiple Gist Environments.
>
> On Windows, this is %APPDATA%\Code\User\syncLocalSettings.json.
>
> Mac, $HOME/Library/Application Support/Code/User/syncLocalSettings.json.
>
> Linux, ~/.config/Code/User/syncLocalSettings.json.

The above paths are hard coded by Settings Sync in [`environmentPath.ts`](https://github.com/shanalikhan/code-settings-sync/blob/777c8cb24b5682f745a1df717a3e7228227c9e90/src/environmentPath.ts#L86). Ideally the extension itself would allow for customization of the target `User` folder, but unfortunately it does not atm.

The usage of the `--user-data-dir` and `--extensions-dir` is apparently not supported by Settings Sync, and that issue is being tracked [here](https://github.com/shanalikhan/code-settings-sync/issues/411).

Following that issue along, Shan (the owner of Settings Sync) reported that this feature is blocked by a lack of support for determining local vs global installations via VS Code itself, which is being tracked [here](https://github.com/Microsoft/vscode/issues/66029).

As of the time of writing, the last update from VS Code was on [Jan 24th](https://github.com/Microsoft/vscode/issues/66029#issuecomment-457124851), so there's no telling when that will be supported. It's a relatively niche feature request, so I doubt they're racing to introduce it.

I find it interesting that I recieve the `Cannot read property 'token' of undefined` error using Official VS Code as well, and i'm currently running Settings Sync version 3.2.7. However, after going through the configuration process, it works just fine.

======

Settings Sync does not support variable extension paths, and the code-server binary is expected to be installed in one of three statically linked locations. When the binary is not found, the binary path it attempts to use is broken. Settings Sync may be more resilient in this regard, if it had a fallback for determining the location of the binary. Unix's `which` command comes to mind. Off the top of my head, I don't know what the most appropriate solution would be for Windows installations. Unfortunately there's only so much extensions can do to resolve the binary's path without a proper API from VS Code itself.

The `--install-extension` flag is not currently supported by code-server. I believe that will have to be implemented, in order for Settings Sync to install extensions by ID after it finds the correct code-server binary. This is due to Settings Sync's ProcessInstallationCLI accessing the global Node Process to get the parent executable [here](https://github.com/shanalikhan/code-settings-sync/blob/425a4144ac1a01379c3db9421e30bd5675bf7da9/src/service/pluginService.ts#L295). Issue https://github.com/codercom/code-server/issues/171 asked for this feature.

**Comment by foresthoffman** [comment]
@neighthan The same functionality can be provided by Coder's sshcode CLI: https://github.com/cdr/sshcode, therefore i'm closing this.

Thanks!
