### ISSUE TITLE
Add grain-lang extension

### ISSUE THREAD

**Issue by ng-marcus** [cdr/code-server#2519]
- [ ] Extension name: Grain
- [ ] Extension GitHub or homepage: https://github.com/grain-lang/grain-language-server

Also on VSX: https://open-vsx.org/extension/grain-lang/vscode-grain

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing it via the code-server CLI as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension) for more info.

Since it's also on Open-VSX, you can switch to it in advance ([docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#how-do-i-configure-the-marketplace-url)) as long as all other extensions you need are on Open-VSX already.
