### ISSUE TITLE
Creating instances of code server dynamically on demand

### ISSUE THREAD

**Issue by redbastie** [cdr/code-server#2558]
What would the best approach be to create something similar to stackblitz?

For example, someone visits my website and clicks "new project". You can see stackblitz creates a new sub domain each time. 

Would I spin up a vm or something each time? What is the best approach for this? And how do I ensure that the user cannot run any exploits that would effect any other sub domain?

Thank you.

**Comment by code-asher** [comment]
Normally I'd convert this to a discussion but for some reason that option has disappeared. 😕 

I'll close this since it's not an issue we can act on but definitely feel free to continue the conversation here.

As to your question, I'm no security expert but VMs should sufficiently protect against those sorts of exploits.

https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#multi-tenancy

There are a few people who have done pretty much exactly what you're thinking and it seems to work out well: https://github.com/cdr/code-server/issues/792
