### ISSUE TITLE
Unable to upgrade to vscode 1.52.1, git error.

### ISSUE THREAD

**Issue by aflextr** [cdr/code-server#2578]
Hello there,
I'm getting git error when updating vscode 1.52.1. Can you help me?

-->
![error](https://user-images.githubusercontent.com/53778891/104506638-b744fe80-55f6-11eb-9049-43fc8896eea1.PNG)

- Web Browser:Chrome 
- Local OS: Windows 10
- Remote OS:Ubuntu:18.04
- Remote Architecture:
- `3.8.0 c4610f7829701aadb045d450013b84491c30580d`:

**Comment by code-asher** [comment]
You'll need to clone the repository to perform git operations. You won't
be able to run it on an installed code-server since it doesn't include
the git data.

Updating also means resolving a bunch of conflicts but you could try
checking out my branch here which has an updated VS Code: https://github.com/cdr/code-server/pull/2543

Everything works except the vscodevim extension which requires an update
to be deployed to our marketplace.
