### ISSUE TITLE
Nix package

### ISSUE THREAD

**Issue by srid** [cdr/code-server#258]
Would be really nice to have a NixOS package that makes it easy to run the server with as simple as adding one line of configuration. The nix package will also be installeable on Mac.

**Comment by elseym** [comment]
had the same thought today, already looking into it together with @Ma27

**Comment by sr229** [comment]
NixOS packages are just AppImages. @nhooyr stated they won't like to suppprt every use case so build your own deployment solution @srid

**Comment by Ma27** [comment]
> NixOS packages are just AppImages.

I'm afraid that this is wrong. Nix is a package manager for several *NIX systems, but with an [entirely different packaging approach](https://nixos.org/nix/about.html). Having a Nix package can be helpful, e.g. if somebody wants to deploy `code-server` to a NixOS system.

@elseym and I started to have a look at code-server's build system, but we got stuck while trying to install the `@coder/*` packages into the build environment last friday. We weren't entirely sure how to run the `postinstall` hooks in the build scripts while building with [`yarn2nix`](https://github.com/moretea/yarn2nix).

We'll probably come back to this during one of the next weeks and report back, but if somebody wants to take over, feel free :)

**Comment by ghuntley** [comment]
> NixOS packages are just AppImages.
No, that is factually incorrect.

**Comment by Ma27** [comment]
Btw we actually made a little bit of progress last friday. The current state (squashed, that's why the commit date is still the 16th march) can be viewed here: https://github.com/elseym/nixpkgs/commit/0666bc913fce8561ed3c6fd17afb4a7e7e9f5457 / https://github.com/elseym/code-server/tree/yarn2nix

We failed at the point where we `node-gyp` was used to build one of the binaries. We assume that either some stuff is missing in the Nix build environment or some prebuilt binary breaks as Nix doesn't have common FHS paths such as `/usr`.

We'll probably have some time for further investigation in some weeks unless somebody actually beats us :)

**Comment by nhooyr** [comment]
This should be filed against nixpkgs.

**Comment by tscholak** [comment]
for those who come here like me and are wondering what the current state of nix integration is:
this has been implemented and merged to `nixpkgs` in June, see https://github.com/NixOS/nixpkgs/commit/9e3dd2279529128f5aec584874185b86eaff08aa#diff-00df174f3487aabf2cb861648bf866b91f6817c375c00ab635e8207c0b1ce8ed.

**Comment by nhooyr** [comment]
Thanks for sharing @tscholak

**Comment by itlinux** [comment]
Hello all, 
I know this maybe be a little off topic, since the Live Share is not really open source, but has anyone been able and provide steps to config Live Share with code-server in a docker solution?

Thanks
