### ISSUE TITLE
User login always shows loading

### ISSUE THREAD

**Issue by liceal** [cdr/code-server#2587]
![image](https://user-images.githubusercontent.com/33884851/104684614-5c192600-5734-11eb-819e-8b156a780a77.png)

**Comment by nhooyr** [comment]
Nice catch, we should remove that profile button since we don't have any account support.

**Comment by choilive** [comment]
Hello,

Im interested in contributing to this project. this might be a good first issue. Ill look into it

**Comment by choilive** [comment]
How should this interact w.r.t. issue #2913?

**Comment by jsjoeio** [comment]
@choilive wonderful! We will be happy to guide/assist however you need.

> How should this interact w.r.t. issue #2913?

Great question!

My thinking is this:
1. don't show User login (basically hide/remove it) -> this issue
2. Show icon when signed in with GitHub -> #2913 

That way, we keep them separate and we work on one thing at a time.

Thoughts @code-asher ?

**Comment by jsjoeio** [comment]
@choilive I'll assign this to you and place in the next version milestone (though there's no strict deadline for you of course).

**Comment by code-asher** [comment]
For #2913 I think our original plan was that we would hide the icon completely when not signed in and show it when signed in.

But what we probably want is to still show the icon when not signed in and just have a "log in" button instead of the loading indicator.

But the first solution is probably easier.

**Comment by code-asher** [comment]
Oh but it might make sense to check what VS Code shows when not signed in and emulate whatever they are doing there.

**Comment by flleeppyy** [comment]
Why is there no account support if I may ask? I have all of my settings and stuff synced through GitHub's version of settings sync, and I _kinda_ since I no longer have access to an actual computer (I'm using a district chromebook, basically locked down, can't use Linux Beta or anything) and all I have is a remote server, and I found code-server and decided I could try that and get all my extensions and stuff back.

**Comment by flleeppyy** [comment]
Sorry to go off topic here, but I think my idea of settings sync is a little messed up. There's a Github sign-in in vscode, that syncs your settings and stuff, but theres also a settings sync extension and im confused as to what is being used for syncing my settings and stuff.

**Comment by code-asher** [comment]
I think the settings sync extension came first and then later syncing was added straight to VS Code, which seems to use GitHub.

The reason the support on code-server doesn't always match up with VS Code is that we have to re-implement the closed source portion blindly and there isn't any documentation for it so sometimes things don't work quite right.

For this issue specifically I think the support *is* there, it just doesn't present itself quite right in the UI.

**Comment by code-asher** [comment]
I'm consolidating the issues and making things a bit more clear in https://github.com/cdr/code-server/issues/3418
