### ISSUE TITLE
Update documentation for Expose code-server

### ISSUE THREAD

**Issue by NathanKys** [cdr/code-server#2602]
It seems like changing bind-address in code-server config file `127.0.0.1:8080`(default setting) to `0.0.0.0:8080` allows exposing local machine to the internet without additional setup.
I'm aware of that it is extremely dangerous and also understand the responsibility that developers had for further problems could caused by doing such thing.   
But for noobs like me would have hard time following additional set-ups for exposing code-server in safe ways,   
and for whom using surplus single-board pc, quick setup might be more important than encryption.
So I kindly suggest that adding some lines about real-quick setup by setting bind-addr in code-server config file with **fully imforming about problem that it could cause.**

**Comment by nhooyr** [comment]
I understand setup can be frustrating but it's *extremely* important that you setup code-server securely as otherwise you will give anyone on the internet access.

For anyone running things locally, the default setup just works.

If you're running code-server on a separate machine in the same local network, you should be using SSH forwarding for security anyway. See https://github.com/cdr/code-server/blob/v3.8.0/doc/guide.md#ssh-forwarding

Anything additional I'm hesitant to add to the docs as you *need* to understand what you're doing and when you do, the flags don't really break convention and are very straightforward.

**Comment by nhooyr** [comment]
Even if that local network isn't exposed to the internet! Someone on the network could sniff your plain HTTP packets depending on the layer 2 protocol and gain access to your hardware.
