### ISSUE TITLE
Allow Insecure Localhost

### ISSUE THREAD

**Issue by InTheCloudDan** [cdr/code-server#2617]
I'm trying to run code-server locally and in the common config it calls out `allow-insecure-localhost` when I set this property in the yaml file I get the error below. Is there a way for me to run this without getting the popup notification every time?

```[2021-01-21T15:48:10.517Z] error error reading /home/coder/.config/code-server/config.yaml: Unknown option --allow-insecure-localhost```

- Web Browser:
- Local OS: Catalina
- Remote OS: default docker container
- Remote Architecture:
- `code-server --version`: 3.8.0

**Comment by code-asher** [comment]
Ah yeah we only implement some of the VS Code commands and that's not
one of them.

Currently the only way to avoid the popup is to use https (even with a
self signed certificate; code-server can generate its own if you pass
--cert)or some othere secure context (like `localhost` or `127.0.0.1`).

Since the issue is browser-level there's no way to enable the missing
functionality from code-server's end (there might be a setting in the
browser config you can use but I'm not sure).

We have discussed giving the option to hide the error but decided
against it. Some context:

https://github.com/cdr/code-server/issues/1329
https://github.com/cdr/code-server/issues/2408
