### ISSUE TITLE
Too slow reading directory structures.

### ISSUE THREAD

**Issue by alpaca2333** [cdr/code-server#278]
when opening a large directory the whole interactions could be extremely slow.

**Comment by Multishifties** [comment]
@alpaca2333 Can you give us some details in regards to your hardware and environment? It might help us identify the issue.

Also, VScode has some known performance issues. If it's a native VSCode issue then there's not gonna be a whole lot we can do https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by kylecarbs** [comment]
Part of this will be fixed with some perf improvements being made.

**Comment by sr229** [comment]
@alpaca2333 Hey there, we use VSCode's source, if large directories are your problem that means VSCode is running out of file handles to use. This is documented and there is a known fix. In Coder's side we can't do anything about this.

**Comment by sr229** [comment]
@kylecarbs I think this deals on a known issue within VSCode itself running out of file handles to work with so I don't think this is us.

**Comment by vnijs** [comment]
@sr229 I'm just starting with `code-server` (self-hosted). It looks great but I basically can't browse files from my mounted home directory because is so slow updating the file explorer. Would you mind posting he "known fix" and how it can be applied for `code-server`? Thanks

**Comment by sr229** [comment]
Essentially you need to increase the limit of file handles spawned so the file watcher can't run out of handles. However this can also relate to slow networks (but since we use `vscode-nsfw`, we share the same symptoms with projects that uses it).

**Comment by vnijs** [comment]
Thanks @sr229. Could you perhaps point to some documentation on how to do that?

**Comment by sr229** [comment]
@vnijs https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by vnijs** [comment]
Thanks @sr229. Unfortunately it doesn't look like that is the issue here as my settings are already at the max value of 524,288. FYI I'm running code-server in a docker container with ubuntu 18.04 on a 2018 macbook pro and browsing through files is just *very* slow. The performance issues in the link posted by @Multishifties seem to be focused on extension but I'm not using any. BTW, vscode runs fine "natively" on my mac and the computational work (ML) I do in the docker container also works fine so I doubt it is a resource issue.

**Comment by alpaca2333** [comment]
The newest version seems to work good for now.
