### ISSUE TITLE
Email change with oauth makes all commits made from code-server to show up as someone else on github.

### ISSUE THREAD

**Issue by czho** [cdr/code-server#2982]
## OS/Web Information

- Web Browser: chrome
- Local OS: ubuntu
- Remote OS: ubuntu
- Remote Architecture: x64_86
- `code-server --version`: 3.9.2

## Steps to Reproduce

1. link account to GitHub 
2. change email
3. commit something
4. change back email
5. commits now show up as a different person

if testing this id suggest doing it on an alt so this bug does not affect your account

## Expected

commits show up as me

## Actual

commits show up as another person

## Screenshot

Initially freaked me out because this was a private repo

![Screenshot 2021-03-26 12 42 11 PM](https://user-images.githubusercontent.com/16581723/112671863-bf0ff300-8e30-11eb-8395-a3268b627b1a.png)

## Notes
This is not a security vulnerability to my knowledge it's, it doesn't change privileges it just messes with the email in git. It is impossible for me to fix on my own. I've tried revoking the OAuth tokens, reinstalling my server os to see if it's my end or cdr's end, and it's not me.

This issue can be reproduced in VS Code: n/a

**Comment by jsjoeio** [comment]
That would definitely freak me out as well. Thanks for the report @czho! I've added this to the "On Deck" milestone which means it should get worked on soon (next milestone or after).

**Comment by czho** [comment]
Some more info on this, there is another part of this issue, in my source control section it is impossible for me to commit it just says git.name and git.email doesn't exist so I have to use the terminal to commit. This might go inline with maby somewhere the cdr server loses track of my email and then sets the other users profile as my email in git just for the terminal.

**Comment by code-asher** [comment]
Could you clarify the second step? Are you changing your email on GitHub or with git? (https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git)

**Comment by czho** [comment]
What I did was remove my github email, then change the main email for it. Just a note i reinstalled the os on my server and then reinstalled code-server so its nothing involving git it self, rather for some reason code-server is messing with git in some way.

**Comment by code-asher** [comment]
FYI, VS Code stores the GitHub credentials in the browser so to clear them you'd need to clear local storage and refresh.

So, the issue is that commits are being made with the incorrect email address when your GitHub account is linked, right?

Here's how I tried to replicate:

1. Create a new repository on GitHub
2. Clone it using https (`git clone https://github.com/username/test.git`)
3. Follow the prompt to link GitHub account
4. `cd test`
5. `git config --list`: Verify it's using the global email I have set
6. `touch test`
7. `git add test && git commit -m test` 
8. `git log`: Verify the commit is still using the global email I have set
9. Remove global git config
10. `git config --list` again: Verify there is no email set
11. `echo test >> test`
12. `git commit -am test`
13. `git log`: This time it used my user and hostname for the email

It doesn't look like `git commit` tries to use the oauth'd account details. It only seems to use email set in git`s config. Git doesn't have any restriction on the emails you can use, so if you've set it to `HarukaMa`'s email for example then when you push GitHub will show their username.

**Comment by czho** [comment]
hmmm, I'm not sure how to reproduce it now, i fixed it by changing the name of my vps so the link changed, but I didn't not set my email to anything involving HarukaMa, I assumed it was an issue with oauth cause I couldn't think of anyway that some random person go involved here. I'm closing this because its a fixed issue that I cant reproduce in anyway.
