### ISSUE TITLE
Can't install latest version of ms-toolsai.jupyter

### ISSUE THREAD

**Issue by ismail** [cdr/code-server#3013]
## OS/Web Information

- Web Browser: MS Edge 91.0.838.3
- Local OS: openSUSE Tumbleweed
- Remote OS: Ubuntu 21.04
- Remote Architecture: x86_64
- `code-server --version`: 3.9.2 109d2ce3247869eaeab67aa7e5423503ec9eb859

## Steps to Reproduce

```
> code-server --force --install-extension ms-toolsai.jupyter
Installing extensions...
Installing extension 'ms-toolsai.jupyter' v2021.5.0...
Extension 'ms-toolsai.jupyter' v2021.5.0 was successfully installed.
```

## Expected

Jupyter extension has version 2021.5.0

## Actual

Jupyter extension has version 2021.3, note that even the available version list doesn't show 2021.5.0.

## Screenshot

![Screenshot from 2021-04-01 11-35-50](https://user-images.githubusercontent.com/4255/113274869-721f9700-92de-11eb-9926-6cd22e735eb3.png)

## Notes

I started debugging this after extensions didn't auto-update, manually checking for updates didn't show anything. Restarting the server and trying again didn't work either.

This issue can be reproduced in VS Code: N/A (can't test)

**Comment by jsjoeio** [comment]
I was able to reproduce this locally. I think this is because by default, it installs from Coder's extension marketplace (which we are soon deprecating and moving towards [OpenVSX](https://open-vsx.org/) and guessing we don't have the latest version in there.

## Logs 

```sh
➜  ~ code-server --force --install-extension ms-toolsai.jupyter
Installing extensions...
Installing extension 'ms-toolsai.jupyter' v2021.5.0...
Extension 'ms-toolsai.jupyter' v2021.5.0 was successfully installed
```

## Screenshot

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/113325757-b191b780-92cd-11eb-81b7-b194a4bce1a9.png">

## Notes

I tried downloading 2021.5.0 from [vsixhub](https://www.vsixhub.com/vsix/43174/) and installing from the VSIX file but received an error message:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/3806031/113326242-45638380-92ce-11eb-82aa-15372f3b1387.png">

The latest version may not work until we upgarde to VS Code 1.55. 

## Suggested Workaround

I think the only workaround we can suggest is to use an earlier version of the extension.

## Related

- https://github.com/microsoft/vscode-jupyter/issues/5342
- Possibly related: https://github.com/cdr/code-server/issues/2626

**Comment by ismail** [comment]
Thanks for the great debugging!

**Comment by jsjoeio** [comment]
![image](https://user-images.githubusercontent.com/3806031/113330481-a0e44000-92d3-11eb-94c6-915ab1efc46e.png)

Couldn't have done it with your easy to follow repro steps!
