### ISSUE TITLE
ENDLESS BUGS - UNUSABLE EDITOR

### ISSUE THREAD

**Issue by gordlord** [cdr/code-server#3020]
### BUGGY
Oh my god, people! Guess what? Wanted to code and something doesnt work  like the language server crashing...

This project will _never_ reach an **stable** state. And I have _waited long_ for this to become  a success. **But it is unusable how it is.**

The whole code-server is just a big fat bug, insecure, and has its very own special way of getting extentions to work. Did I mention that several extensions like the C++ plugin do not work at all?
Language server crashes and finally decides to not restart to come to work again! Yea this is the way to go instead of finding the issue. This plugin is supported on my server (linux amd64) but not so on code-server. Even Theia and Gitpot manages to handle extensions correctely! 1+ for them (yes even ms extensions.)

I have not seen any usefull commit in the last months - ignoring the dependabot stuff (that really spamms the commit log rather than being useful) and updating some template or setting for github. all wasted time.
 
Now who can use vscode-server really productively because I really cannot. Not in C++,PHP or Python

**Do me a favor and please stop.**  dont waste your time on what you can **not** finish or even fix.

Im sure a lot of ppl had that to say.

**Comment by oxy** [comment]
Hey, that's kind of rude.

If you have any specific bugs that you've found in our product, I'd encourage you to report them specifically, which would actually help us fix bugs. Just filing a bug that says "your product sucks, give up" is not a nice thing to do in general, and I'd encourage you to either file bugs that provide constructive feedback, or at the very least refrain from flaming.

Many of our issues like extensions don't show up in this commit log because they weren't issues that needed explicit fixes here - for instance, the Python extension bugs were resolved by a VSCode update and some build tweaks on our extension gallery.

I'm locking this issue.
