### ISSUE TITLE
node fails to start on arm64 with android

### ISSUE THREAD

**Issue by agowa338** [cdr/code-server#3030]
## OS/Web Information

- Remote OS: Android with Termux
- Remote Architecture: arm64
- `code-server --version`: 3.9.2

## Steps to Reproduce

1. try to execute `./lib/node`
2. `./lib/node: No such file or directory` is displayed because `/lib/ld-linux-aarch64.so` doesn't exist.

## Expected

code-server starting successfully and node working

## Actual

node failing to start because of missing dynamically linked interpreter `/lib/ld-linux-aarch64.so`

## Notes

The correct linker is `/system/bin/linker64`. But node is also available as an installable package, so using the system provided version of node would also work. I'd suggest trying to use the version from $PATH if `./lib/node` fails to execute.

This issue can be reproduced in VS Code: No

**Comment by oxy** [comment]
This is expected behavior - `lib/node` is the official nodejs build, which builds against glibc, while Termux builds against bionic libc - many of the native libraries VSCode uses to run won't work either, since they're compiled against glibc too.

I'd recommend installing with yarn (`yarn global add code-server`) on Termux - see https://github.com/cdr/code-server/blob/main/docs/install.md#termux. at the moment, we do not build Termux-compatible binaries, though we may consider it in the future.
