### ISSUE TITLE
[dev]: switch from jest-playwright to playwright test

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#3115]
The Playwright team has reached out and suggested we use `playwright-test` instead of `jest-playright` as our test runner. The APIs look similar but they offered to help/guide the migration.

> Hi @jsjoeio! Would you consider trying playwright-test instead of jest-playwright? We at Playwright team believe that with the focused test runner it is possible to deliver better experience for e2e tests. If you are open to this, I can guide/help with the migration, as well as address the feedback on the test runner side 😄 Let me know if you are interested!

Originally posted: https://github.com/cdr/code-server/pull/3016#issuecomment-816329571

Note: I'll probably start on this sometime this week and post thoughts and ask questions as I go here.

**Comment by jsjoeio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [code-server: switch from jest-playwright to playwright test](https://trello.com/c/NqOBxHxe/32-code-server-switch-from-jest-playwright-to-playwright-test)

**Comment by jsjoeio** [comment]
## Migration Process

Placeholder

**Comment by jsjoeio** [comment]
## Feedback

Placeholder

**Comment by dgozman** [comment]
Thank you for the feedback! I have a few comments/questions, but we'll address most of the items.

- The config file is a deliberate decision. I understand that it might feel unfamiliar, but some documentation is already there and we'll expand it. I hope that it will feel much better once you'll get to use any flexibility that it provides.

- We are not providing any globals, instead you should be able to import whatever you need - this is a deliberate decision as well. This allows us to isolate tests, run them separately or together, rerun flaky failures and more.

> - How do I know what test passed?

What specifically do you want to see? All the tests with green checkmarks? Try running as `npx folio --reporter=list`. There are a few built-in reporters available, and the default one (`--reporter=line`) is good for large test suites - for example we use it for our test runs with 1800 tests, where spamming the terminal is not an option. There is an [initial example](https://github.com/microsoft/playwright-test#export-junit-report) about using reporters, feel free to play with it.

> - How many tests were there in total?

It says `Running 1 test...`

> - What browser was used?

This depends on your config - most likely all three browsers. The test name should be prefixed with something like `[chromium]` when it runs under Chromium. Do you want to see just the browser or something else?

**Comment by jsjoeio** [comment]
Thanks for the response @dgozman! 

> we'll expand it. I hope that it will feel much better once you'll get to use any flexibility that it provides

I think you're right. I'm already starting to see some of the benefits of the flexibility provided by the config file.

> This allows us to isolate tests, run them separately or together, rerun flaky failures and more.

Awesome! I figured out how to get the `browserName` luckily, but some docs on that would be nice. 

> Try running as npx folio --reporter=list

That worked! Thanks!

> What specifically do you want to see?

Honestly, I wish `folio` had `--reporter=jest` so that I could get a jest-like reporter out of the box. I like the green checkmarks and the `PASS`.

> How many tests were there in total?

Sorry, this was vague. Basically, I wish it was more like Jest.

```
Test Suites: 1 skipped, 11 passed, 11 of 12 total
```

> The test name should be prefixed with something like

Oh yeah, that's what I'm looking for, but I'm not seeing it.

![image](https://user-images.githubusercontent.com/3806031/114637862-2aeeba00-9c7f-11eb-99c4-9259056a7148.png)

P.S. I added more feedback to my comment above under `UPDATE`

**Comment by jsjoeio** [comment]
@dgozman we've migrated over! Thanks so much for your help.

**Comment by dgozman** [comment]
@jsjoeio Great! Thank you for your feedback. We'll keep addressing it, and I will comment here with an update.

**Comment by dgozman** [comment]
@jsjoeio Thank you for trying the previous experimental version, your feedback **helped a lot**! We've been working on the next version, and a new alpha is ready. If you enjoy `@playwright/test` so far, you should give this one a try. The new alpha is versioned `0.1112.0-alpha1`.

[Here is a preview](https://gist.github.com/dgozman/fc0f3c2770d4f90f2c85453b55ac2c9e) of the upcoming documentation and migration guide. However, since you have tried the experimental version (thank you!), migration will be a bit different for you:

- Configuration file format has changed, please see an example in the documentation above. Overall, it should be a bit easier now. [More details about configuration](https://github.com/microsoft/folio#configuration-object).
- Instead of passing options as a second parameter to the `test('title', options, func)`, you should now call `test.use(options)` to declare options for a file or a describe block.
- `globalSetup` / `globalTeardown` now lives in a separate file. [More details about global hooks](https://github.com/microsoft/folio#global-setup-and-teardown).
- If you have started using custom environments, you'll have to switch to fixtures. That's somewhat involved, and reading [Folio documentation](https://github.com/microsoft/folio) is necessary.

Let me know if you are willing to try this, and send me all the questions.

--- 

Answering some of the older questions, based on the new version:
- > `'const' enums are not supported`. getting this when importing a variable from an external file that uses an enum.

  I guess this is a babel thing. We have bumped the babel version, let me know if this still happens.

- > wish the docs explained how to resetContext before running a test (ensure cookies are cleared)

  This is done by default. Each test is isolated from others.

- > config option to choose name of video directory - I want them to be stored under `/videos`

  This is not done yet. You should get videos per test in `test-results/test-file-test-name` directories.

- > docs only show `npm install`. show `yarn` too

  Not done yet.

- > Honestly, I wish folio had `--reporter=jest` so that I could get a jest-like reporter out of the box. I like the green checkmarks and the `PASS`.

  No significant progress on reporters, but we'll focus on them soon.

**Comment by jsjoeio** [comment]
Awesome! Thanks so much for the reply @dgozman - I'll open a separate issue to track upgrading to the new alpha version and tag you with questions after.
