### ISSUE TITLE
Cannot find some extensions

### ISSUE THREAD

**Issue by yzgyyang** [cdr/code-server#3295]
## OS/Web Information

- Web Browser: Chrome Version 90.0.4430.93
- Local OS: Windows 10 Version 20H2
- Remote OS: FreeBSD 13.0-RELEASE
- Remote Architecture: amd64 (Virtualbox)
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. Search `sml` in the extension tab.

## Expected

Here is a screenshot of the search results from vscode (both FreeBSD and Windows):

![image](https://user-images.githubusercontent.com/16748524/117180212-f4015500-ada1-11eb-80e3-3d022adcc8a2.png)

## Actual

Here is a screenshot of the search results from code-server:

![image](https://user-images.githubusercontent.com/16748524/117180280-07acbb80-ada2-11eb-989f-56ab492f929f.png)

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Hey @yzgyyang this is because we use a different marketplace than VSCode so this is expected behavior. 

Please see ["Differences compared to VS Code?"](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#differences-compared-to-vs-code) and ["Installing an extension manually"](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension-manually) if you can't fin what you're looking for.

**Comment by yzgyyang** [comment]
Thanks! Did not know that code-server uses a different marketplace due to Microsoft. Sorry for the noise!

**Comment by jsjoeio** [comment]
No worries at all - it's hard to tell!
