### ISSUE TITLE
Various Files Reporting 404

### ISSUE THREAD

**Issue by TolleyCoding** [cdr/code-server#3328]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu Server 20.04
- Remote Architecture: x64
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. Install Code-Server
2. Having it working for a while
3. Try to connect one day, enter password, blank screen.

## Expected

Perfectly Functional Server

## Actual

Blank Screen

## Log + Info

The server is behind an nginx proxy. The server used to be functional, when I go to one of the URLs reported as a 404, I receive: `{"error":"ENOENT: no such file or directory, open '/usr/lib/code-server/lib/vscode/out/vs/base/common/lifecycle.js'"}`. I have checked the folder it is looking for, and it indeed does not contain those files. Issue #1640 seems to have a similar issue, yet was fixed with an update.

Browser Log: (domain cropped off)
![image](https://user-images.githubusercontent.com/39429061/117565684-6deb5400-b0aa-11eb-927c-785444b5a959.png)

**Comment by TolleyCoding** [comment]
Also forgot to note that I have tried the steps in #1836

**Comment by code-asher** [comment]
Is there some kind of timeout or error in the network tab for `workbench.web.api.js`?

In my experience this happens because the main bundle fails to download so VS Code tries to request the individual files instead but we only ship the bundle, not the individual sources.

It should get cached though so theoretically if you've successfully loaded once it should keep working unless the cache was cleared.

This might have something to do with how we load the workbench in `vscode.html`. It deviates slightly from how VS Code does it in production so we should take a look at that.

**Comment by TolleyCoding** [comment]
Oh, or not, http2_protocol_error is causing `workbench.web.api.js` to not load, Chrome just decided in it's infinite wisdom to not highlight that. Gonna look deeper into my NGINX config

**Comment by code-asher** [comment]
Do you have any idea if this happens when you access code-server directly without a reverse proxy?

It might also help to check the proxy logs to see if it says anything about that request.

I wonder if you try to open `workbench.web.api.js` directly in a new tab if it works? I'm not sure what this would tell us though.

As for headers I don't think we send `content-size` and the others don't look like they should cause any issues but I'm not sure.

**Comment by MxD-js** [comment]
Hmm. I cannot say that I am getting the same thing. I am also using Nginx as reverse proxy w/ HTTP/2 enabled. Mainly using reverseproxy for the ssl part.

**Comment by TolleyCoding** [comment]
Sorry for the late response, but I can confirm it's something funky with the proxy. Directly accessing the server works fine. I'll close this since it's something on my system.
