### ISSUE TITLE
Process is named node instead of code-server

### ISSUE THREAD

**Issue by georgebushfourtwenty** [cdr/code-server#3415]
## OS/Web Information

- Web Browser: any
- Local OS: linux
- Remote OS: linux
- Remote Architecture: x86_64
- `code-server --version`: 3.10.0

## Steps to Reproduce

1. Start code-server
2. Query the running process list

## Expected
Process must be named code-server.

## Actual
Named node instead.

I'm not sure if this was intended, just bringing it to your attention.

**Comment by code-asher** [comment]
Ah yup we run code-server using Node so this is intentional.

We could maybe work around this by renaming the Node binary we ship or some other trickery but personally I think we should leave it as-is since it's more transparent.

Thank you for bringing this up! I'll close but please feel free to comment if you disagree.
