### ISSUE TITLE
README image appears to be blurry

### ISSUE THREAD

**Issue by agneevX** [cdr/code-server#4117]
The README image appears to be blurry.

<img width="698" alt="Screen Shot 2021-09-08 at 8 00 21 PM" src="https://user-images.githubusercontent.com/19761269/132528935-3e5d8760-fd23-48b4-832d-17226964cba9.png">

Not sure how #4036 got merged. Seems to be a misuse of SVGs.

**Comment by jsjoeio** [comment]
> The README image appears to be blurry.

Maybe there is an issue with your browser? I'm seeing a clear image here. 

![image](https://user-images.githubusercontent.com/3806031/132585492-e5714bc0-d65f-44bf-b203-78cca76542b3.png)

> Not sure how #4036 got merged. Seems to be a misuse of SVGs.

Could you please clarify on why this is a misuse of SVGs?

**Comment by agneevX** [comment]
It's Safari 14.1.2 on a Retina display. 

This is misuse because SVGs are used for icons or web assets that need to scale dynamically. These shouldn't be used for a screenshot or any thing related. 

For a README, a JPEG or PNG should be used, with a considerable amount of compression.

**Comment by jsjoeio** [comment]
> This is misuse because SVGs are used for icons or web assets that need to scale dynamically.

Actually, you can use them for more than just icons or web assets! I'd encourage you to check out the [SVG docs in MDN](https://developer.mozilla.org/en-US/docs/Web/SVG). SVGs are always nicer because they scale better and are smaller, plus we can do fancy animations like the [Expo CLI project](https://github.com/expo/expo-cli).

> For a README, a JPEG or PNG should be used, with a considerable amount of compression.

I don't agree. You can use other formats too if they're used correctly, but I agree compression is important. 

Regardless, I took a closer look and it's not a _true SVG_ as we thought it was so it probably makes sense to use a PNG, which would fix the blurriness on your screen. Thanks for bringing it up!

**Comment by agneevX** [comment]
Appreciate it, Joe 👍

**Comment by jsjoeio** [comment]
No, thank you! 🙌 

We wouldn't have known it could be an issue without your bringing it up! Enjoy the rest of your day!

**Comment by agneevX** [comment]
@jsjoeio what theme are you using?
