### ISSUE TITLE
iPad/iOS 15 hardware keyboard leaves white bar at bottom of screen

### ISSUE THREAD

**Issue by oeed** [cdr/code-server#4272]
## OS/Web Information

- Web Browser: iOS PWA
- Local OS: iOS 15.0
- Remote OS: macOS 11.2.1
- Remote Architecture: Intel x64
- `code-server --version`: 3.12.0

## Steps to Reproduce

I've only just started using code-server so sorry if this is a known issue, the closest issue I could find was #3272, but that appears to be a different iOS version. My guess is maybe this bar was to compensate for pre-iOS 15 keyboard widget layout?

1. On an iPad with a keyboard connected (Magic Keyboard in this case), focus a text field.
2. A white bar at the bottom of the screen will appear along with the little keyboard widget.
3. Once deselecting the text field the bar will go away.

## Expected

I would hope that the Code window would cover the whole screen. I know the keyboard widget is probably unable to be removed however; you can minimise this widget to just be a little icon in the corner which is perfectly fine.

## Actual

A white banner at the bottom of the screen appears, reducing available screen area.

## Logs

Doesn't seem likely to be relevant but can provide if needed.

## Screenshot

https://user-images.githubusercontent.com/3835991/135344460-93af0bf1-30d1-4cc8-a89e-ef4cd0772016.mov

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Thank you for the detailed issue and the video! It makes our lives SO much easier ♥️

I feel like this is an iOS level setting that may be configure somewhere in the settings (AFAIK, there's nothing inside code-server that _should_ trigger this). I'm not sure _exactly_ which setting it is, but here's a video of my Settings

My best guess is to turn off "Show Onscreen Keyboard" under Accessibility > Touch > AssistiveTouch

https://user-images.githubusercontent.com/3806031/135356604-745272a8-057b-483a-8f96-65d6370c799e.MP4

Let me know if that works or if you figure it out!

**Comment by oeed** [comment]
Unfortunately 'Show Onscreen Keyboard' was already off, I tried turning it on but that didn't help either.

I tried using the Safari web inspector from my Mac to inspect Safari on my iPad, but for some reason the inspector crashes on code-server. I'll try update Xcode to get the iOS 15 simulator and see if I have any luck there.

One observation though is on iOS 14 at least, the height on `.monaco-workbench` is being set to (what seems to be) `window.innerHeight` on change, so perhaps Safari is misreporting that value. Will come back with further results.

**Comment by jsjoeio** [comment]
Bummer! I was hoping it might be that.

> One observation though is on iOS 14 at least, the height on .monaco-workbench is being set to (what seems to be) window.innerHeight on change, so perhaps Safari is misreporting that value. Will come back with further results.

Interesting! I wonder if that's it. I did find [this article](https://itnext.io/make-your-pwas-look-handsome-on-ios-fd8fdfcd5777) where they say:

> The hack: Set the minimum height of the document to 100% plus the height of the safe area on top. This will prevent a white bar in the bottom which gets shown since you moved the document “up”.

Do you have access to GitHub Codespaces? I wonder if that happens there as well. I did find this [old issue](https://github.com/microsoft/vscode/issues/122390). 


Also I think I misunderstood your original question. I see two "white bars" - the big one is the one I _thought_ you were referring to, which is why I said I think this is iOS Settings related. But, it sounds like you're talking about the skinny one, right?
![bars](https://user-images.githubusercontent.com/3806031/135501731-6e077c8c-f2f0-448c-b34c-9d66ec4bed70.jpg)

In that case, it seems like this should have been fixed in [1.60.2 ](https://github.com/microsoft/vscode/commit/dbed1fbe954fdd34b05deeb273198d4f539a6173)

But code-server is only on v1.60.0 so this wouldn't be fixed until we upgrade VS Code.

**Comment by oeed** [comment]
No unfortunately I don't have access to Codespaces. That issue does look exactly like the issue, it was indeed about the skinny bar, rather than the larger iOS one. Great to see it's likely fixed upstream!

What's the rough update cycle like for updating the VSCode version?

**Comment by jsjoeio** [comment]
> What's the rough update cycle like for updating the VSCode version?

Good question! @TeffenEllis is working on updating us soon (I think) so it should be updated in the next release (but I'll let Teffen confirm). 

We try to keep up with their releases as best we can.
