### ISSUE TITLE
Accelerate release rhythm

### ISSUE THREAD

**Issue by woshiniming007** [cdr/code-server#4429]
With the current release rhythm, we are unable to keep up with the latest VSCode releases, for example we have skipped bug fix version 1.54.3 and 1.56.2.

**Comment by jsjoeio** [comment]
Yeah, this is definitely something we're working on. The reason the rhythm is so slow currently is because we're rearchitecting the way we consume/use VS Code in code-server. Apologies with the delay. After this next release, it should be a lot more in line with VS Code's. Follow [this PR](https://github.com/cdr/code-server/pull/4414) for our current status.

**Comment by woshiniming007** [comment]
> Yeah, this is definitely something we're working on. The reason the rhythm is so slow currently is because we're rearchitecting the way we consume/use VS Code in code-server. Apologies with the delay. After this next release, it should be a lot more in line with VS Code's. Follow [this PR](https://github.com/cdr/code-server/pull/4414) for our current status.

Thanks for relpy, your work on vscode really helps a lot!
