### ISSUE TITLE
product.json location

### ISSUE THREAD

**Issue by grahampcharles** [cdr/code-server#4431]
In the documentation about how to point code-server to a different extension gallery (https://coder.com/docs/code-server/latest/FAQ#how-do-i-use-my-own-extensions-marketplace), reference is made to either setting environment variables (which works fine) or setting values in `product.json`. There does not seem to be such a file in `~/.local/share/code-server` and I cannot locate where it is supposed to be. Can its typical location be documented?

**Comment by jsjoeio** [comment]
I think there is some misunderstanding. The docs read

> **If you own a marketplace that implements the VS Code Extension Gallery API, you can point code-server to it by setting $SERVICE_URL and $ITEM_URL**. These correspond directly to serviceUrl and itemUrl in VS Code's product.json.

You can't modify the `product.json` in your instance of code-server but these values (the default values) live in `product.json`. 

Hope that makes sense! I'm going to close this.

**Comment by grahampcharles** [comment]
No, not really. I think the docs should include that file's location -- I certainly can't find it.

**Comment by jsjoeio** [comment]
> No, not really. I think the docs should include that file's location 

Sorry, maybe it wasn't clear in my last message. I can see why it would be confusing. We **don't recommend editing the product.json**. This would be the equivalent to editing the source code and is not recommended because we can't guarantee things will still work after. And JSON (as you probably know) is fragile so I wouldn't recommend changing that file.

You **should** use the environment variables, which is why that's the only thing in the docs.

**Comment by grahampcharles** [comment]
I see. Then I think the reference to `product.json` should be removed as extraneous.

**Comment by jsjoeio** [comment]
Good point! I'll reopen and track here
