### ISSUE TITLE
Fix service worker path for reverse proxy

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4477]
Reverse proxy: service worker with base path fails due to incorrect scope

@code-asher may have more details.

Introduced in #4414

**Comment by code-asher** [comment]
To test:

1. Spin up NGINX/Caddy/etc
2. Serve code-server at a base path like /code
3. Observe the service worker error

**Comment by jsjoeio** [comment]
I cannot reproduce this. 

![image](https://user-images.githubusercontent.com/3806031/143143673-e626abde-f628-4a3e-b9bd-6ebcba8b9162.png)

It appears that the service worker uses a [relative path for the scope](https://github.com/cdr/vscode/blob/main/src/vs/server/webClientServer.ts#L312) so maybe this is no longer an issue?

**Comment by code-asher** [comment]
Ahhh this is probably because I was browsing `/code` and not `/code/` (trailing slash).

I thought we supported this (no trailing slash on a base path) but I checked 3.10.2 and we do not.  In hindsight that makes sense since we do not know what the base path is so we require the trailing slash (on the base path at least, we can still support no trailing slash on our own routes if we want).
