### ISSUE TITLE
Unable to secure using self signed certificate on Ubuntu 16.04

### ISSUE THREAD

**Issue by curlybraces** [cdr/code-server#451]
- `code-server` version: 
- OS Version: 
Ubuntu 16.04

## Description

Followed steps to secure code-server, but when I launch code-server --cert=~/certs/MyCertificate.crt --cert-key=~/certs/MyKey.key 

It tells me the file already exists. It creates a ~ on my home directory.

## Steps to Reproduce

Followed steps provided
1. 
1.

**Comment by code-asher** [comment]
This is caused by how shells expand things. (See https://stackoverflow.com/questions/15493928/shell-tilde-expansion-does-not-work-when-passed-as-an-option for details). `code-server` is receiving a literal `~` instead of your home directory.

You can fix it by doing `--cert ~/certs/MyCertificate.crt` or `--cert=$HOME/certs/MyCertificate.crt`.
