### ISSUE TITLE
CoderIDE (Docker) + CloudFlare Too Many Redirects error.

### ISSUE THREAD

**Issue by jackmerrill** [cdr/code-server#575]
- `code-server` version: Latest from Docker
- OS Version: 18.09.2

## Description

I am using Docker to host and run my Code-Server instance and I have CloudFlare for DNS, and Bouncy (NodeJS) for internal routing. When I try to access my the IDE through a domain, I get a "Too Many Redirects" error from Chrome. I am unsure about what is causing this issue, whether it is CloudFlare, the IDE, or Bouncy.

## Steps to Reproduce

1. Install Code-Server through Docker (I used Portainer)
2. Use Bouncy to bounce the port from 80 to 8443
3. Add subdomain to Cloudflare (I used ide.[website].com)
4. Wait until the DNS reloads.

Any help is appreciated.

Thanks!

**Comment by justinmoon** [comment]
I've been getting "too many redirects" errors as well ...

**Comment by dtwilliams10** [comment]
same here

**Comment by boop5** [comment]
+1

**Comment by jackmerrill** [comment]
This thread is almost a month old, and Docker is the fastest way to deploy the code-server repository. They should have at least seen this by now.

**Comment by erwinverdonk** [comment]
Same issue here when using a proxy server in front. Not sure what causes it though, but it seems to be related to being proxied.

**Comment by deansheather** [comment]
If you're using a reverse proxy, I'd recommend adding `--allow-http` when starting code-server and then reverse proxying over HTTP instead of HTTPS. In cases like this, redirect loops often happen when the app is being accessed over a HTTP port by the proxy but the app is setup to redirect to HTTPS.

When you add Cloudflare into the mix, you can get redirect loops if your Cloudflare is setup on Flexible SSL and your origin redirects from HTTP to HTTPS. If you have a valid HTTPS server running a valid cert or a Cloudflare origin cert, you should change your SSL setting to Full or Full (Strict). An easy way to check if it's Cloudflare's fault is to disable Cloudflare protection or access the site directly.

**Comment by jtbrne** [comment]
--allow-http resolved the issues for me.

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.
