### ISSUE TITLE
Is ide.coder.com shutting down?

### ISSUE THREAD

**Issue by BinaryBen** [cdr/code-server#657]
When logged into ide.coder.com, there is a message in the top right that "Coder hosted will be ending on May 5th" and a link to self-host.

That date has passed, but for clarification, does that mean existing account holders won't be able to access the hosted installation of code-server in the imminent future? Or does Coder hosted refer to something else?

**Comment by coadler** [comment]
Yep, it means existing account holders won't be able to access ide.coder.com anymore.

When it happens, you'll be able to contact us to retrieve your files back if you haven't downloaded them already.

I'm not sure *exactly* when it will happen but I expect soon-ish

**Comment by BinaryBen** [comment]
Is there likely to be anything hosted offered again?

**Comment by sr229** [comment]
@BinaryBen There isn't any plan as of this moment for a hosted Coder service.

**Comment by wadeziegler** [comment]
Why is it shutting down? This is such a good product.

**Comment by sr229** [comment]
It's hard to run a hosted IDE product like Coder @wadeziegler, while we do have a good premise for a product, the costs to run hosted IDEs are larger than usual apps. To give you an idea, look at how GCP prices VM instances. The reason why people like TypeFox can run because they have large corporate backing already (Red Hat usually for TypeFox), Coder simply don't have that large corporate backing to run such services.
