### ISSUE TITLE
Any way to store tokens?

### ISSUE THREAD

**Issue by roberthmiller** [cdr/code-server#709]
I use extensions such as GitHub-pr and quokka which require a token. Is there any way to persist this across sessions?

**Comment by deansheather** [comment]
By "across sessions" I assume you mean across Docker containers or something similar, as these secrets should persist across sessions on the same machine/container.

Microsoft's GitHub PR extension seems to use keytar as a backend, which uses the system's keychain (or libsecret on Linux) to store secret data. I don't believe keytar supports copying data across machines.

I'm unable to see how Quokka stores it's authentication token since it doesn't seem to be open source and I don't have a Pro subscription. I'd imagine that if they aren't using `config.json` for storing the token they'd be using Keytar instead.

**Comment by roberthmiller** [comment]
I guess across docker containers. I was mainly coming across this issue when rebuilding sail docker images. How would you recommend that I go about "forwarding" it?

**Comment by deansheather** [comment]
Keytar is using libsecret, which in turn uses [secret service](https://specifications.freedesktop.org/secret-service/) via D-Bus. This protocol doesn't have a method of exporting data for copying/forwarding to another machine, and I'm not sure how to do it otherwise.

Maybe you could forward a D-Bus socket from the host to the container, but I don't know if that would work.

**Comment by roberthmiller** [comment]
too much just to make some extensions work :nauseated_face:
