### ISSUE TITLE
change 'lib'，how to solve this problem?

### ISSUE THREAD

**Issue by michaelchou** [cdr/code-server#743]
## Description

![屏幕快照 2019-06-03 下午1 51 26](https://user-images.githubusercontent.com/1912866/58779094-62ae6480-8607-11e9-92fe-b371a86f6f6f.png)

**Comment by EdByrnee** [comment]
did you find a solution?

**Comment by EdByrnee** [comment]
Fixed by bumping typescript down to 3.3.3

In bottom right, click on the version number to change, but first we must npm install -g typescript@3.3.3

Now tell vs about this new version by F1-> open user preferences -> search for typescript.tsdk update .json to 

{
    "typescript.tsdk": "/home/ubuntu/.nvm/versions/node/v8.15.1/lib/node_modules/typescript/lib"
}

Now reopen file and change typescript version at bottom right, this will resolve the problem!

**Comment by michaelchou** [comment]
> Fixed by bumping typescript down to 3.3.3
> 
> In bottom right, click on the version number to change, but first we must npm install -g typescript@3.3.3
> 
> Now tell vs about this new version by F1-> open user preferences -> search for typescript.tsdk update .json to
> 
> You can get npm global install path with npm root -g
> 
> {
> "typescript.tsdk": "/home/ubuntu/.nvm/versions/node/v8.15.1/lib/node_modules/typescript/lib"
> }
> 
> Now reopen file and change typescript version at bottom right, this will resolve the problem!

Thank you!!! I resolve this problem according to the way.

**Comment by yw662** [comment]
Update: typescript@3.5.1(which is used by vscode) and  typescript@3.5.2 can also solve this issue.

Which means, code-server can solve this by updating underlaying vscode version.
