### ISSUE TITLE
Failed to apply patches

### ISSUE THREAD

**Issue by crytt** [cdr/code-server#805]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: Windows 10

## Description

Trying to `docker build .` results in:

> ERROR VSCODE:PATCH Failed: Failed to apply patches: /src/scripts/vscode.patch:6: trailing whitespace.
> export const isMacintosh = userAgent.indexOf("Macintosh") >= 0;
> /src/scripts/vscode.patch:7: trailing whitespace.
> export const isWindows = userAgent.indexOf("Windows") >= 0;
> /src/scripts/vscode.patch:8: trailing whitespace.
> export const isLinux = userAgent.indexOf("Linux") >= 0;
> /src/scripts/vscode.patch:9: trailing whitespace.

**Comment by deansheather** [comment]
Could it be git checking it out with CRLF line endings instead of LF (default in Git for Windows)? I'm unable to reproduce this on Debian.

Try adding `--whitespace=fix` to the `git apply` args list in [build/tasks.ts](https://github.com/cdr/code-server/blob/master/build/tasks.ts#L179) and see if that helps. If it does, it should be safe enough for us to merge that into master so people building on Windows don't run into this problem in the future.

**Comment by crytt** [comment]
Adding `--whitespace=fix` to the git apply arguments list seems to have worked.

Thanks, Dean! :)

**Comment by deansheather** [comment]
Could you open a PR so we can merge this in?
