### ISSUE TITLE
`vscode-resource` scheme is unknown 

### ISSUE THREAD

**Issue by trinhpham** [cdr/code-server#817]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: CentOS 7.5 with Docker 18.09.6

## Description
I am creating VSCode extension which loads [webview's local content](https://code.visualstudio.com/api/extension-guides/webview#loading-local-content).
When trying it with coder, I saw that browser cannot understand this scheme, so my resources cannot be loaded.
![image](https://user-images.githubusercontent.com/9128061/60330311-5f1abd00-99bc-11e9-93a5-0f7a6c1e6a9b.png)

## Steps to Reproduce
Give a try on extension that has local contents as [this guide](https://code.visualstudio.com/api/extension-guides/webview#loading-local-content)

**Comment by tiagobento** [comment]
I'm having the same issue. In my case I can load the local content inside the `webview.html` property, but if I try to dynamically create a <script>, I get the same error showed on the picture above.

**Comment by trinhpham** [comment]
I found that if I put my resources inside a pair of double quotes, they can be loaded successfully.
Coder team has handled it at [this line](https://github.com/cdr/code-server/blob/f25a614333aa9599906d077c4aa7808a5f1688a8/packages/ide/src/fill/electron.ts#L153)

**Comment by tiagobento** [comment]
@trinhpham Thanks for the comment. Surrounding the path with double quotes definitely did something, but not quite what I expected.

I have the following code running:

```typescript
const script = document.createElement("script");
script.src = `"${path}"`;
script.type = "text/javascript";
document.body.appendChild(script);
```

When `path` is
```
vscode-resource:/home/coder/.local/share/code-server/extensions/kiegroup.appformer-js-vscode-extension-0.0.0/dist/webview/editors/dmn/org.kie.workbench.common.dmn.showcase.DMNShowcase/org.kie.workbench.common.dmn.showcase.DMNShowcase.nocache.js
```

Then the resource that Coder tries to download is: 

```
http://localhost:8443/packages/ide/src/fill/%22vscode-resource:/home/coder/.local/share/code-server/extensions/kiegroup.appformer-js-vscode-extension-0.0.0/dist/webview/editors/dmn/org.kie.workbench.common.dmn.showcase.DMNShowcase/org.kie.workbench.common.dmn.showcase.DMNShowcase.nocache.js%22
```

Notice that I'm doing all that inside the WebView. Take a look:

![image](https://user-images.githubusercontent.com/1584568/61078019-0bfe2c80-a3f6-11e9-8b58-2884867180ef.png)

I tried to find somewhere in the code where there's a URL encoding happening to the `src` string but no luck :(

**Comment by deansheather** [comment]
@tiagobento Check the lines you pasted into the console. `script.src` doesn't have a trailing `"`.

**Comment by trinhpham** [comment]
@tiagobento I have no much experiment to help you on this. But I can see that:
1. The URL is updated => the code has worked
2. `%22%` means double quotes => Somehow the string you give has been wrapped twice

Hope this can help.

**Comment by tiagobento** [comment]
@deansheather Thanks Dean! I just tried it with the trailing quotes and it changed, but didn't quite work yet. Check the screenshot below.

@trinhpham Thanks for helping me out with that! From the screenshot below I can only assume that any string that starts with `"` will be changed, because when I do `script.src = ...`, nothing happens to the HTML attribute, but when the browser tries to download the file, it does convert it to URL encoding, which makes sense.

See:

![image](https://user-images.githubusercontent.com/1584568/61131899-ab6ffd80-a490-11e9-9a2a-b28e0f214465.png)

My guess:

[This code](https://github.com/cdr/code-server/blob/f25a614333aa9599906d077c4aa7808a5f1688a8/packages/ide/src/fill/electron.ts#L153) only works when we do `panel.webview.html = ...`, because there we actually have

```html
<script src="vscode-resource:/the/source/to/script.js" ... />
```
In fact, the extension I'm building **does** load a script like that and it works. It's just when I'm trying to _dynamically_ load a script that it doesn't work. Do you guys think that's reasonable?

Thanks again for all your help!

**Comment by deansheather** [comment]
It's definitely an issue with loading the script via a console, as the code in code-server that changes the URL doesn't get executed on stuff you inject through a console.

**Comment by tiagobento** [comment]
@deansheather Yeah.. looks like it. Do you think we should reopen this issue? Or create another one? I read that the contribution guidelines are still on the works for code-server, so please tell me how I should report that.. this is a real blocker for me.

Thanks!

**Comment by deansheather** [comment]
There's not much that we can do about changing script URLs that were injected via the console.

**Comment by tiagobento** [comment]
Hi @deansheather, sure, let me try to explain my use case in more depth.

We provide a custom preview for different file types on Visual Studio Code. When you click a file with a supported extension, a WebView immediately opens with a rendered version of that file.

To do that, we have to dynamically load the scripts related to the file extension that's being opened, so if you open a `.dmn` file, we load `bundled-dmn-diagram.js` and if you open a `.bpmn` file, we load `bundled-bpmn-diagram.js`, and so on.. We have more than one script per file extension and we have css assets that we need to download as well.

Since code-server is replacing the contents of the string we assign to `panel.webview.html`, I figured there would be a way to "intercept" the strings we assign to `script.src` too.. is that possible? If so, we could do the same kind of string replacement to "fix" the `vscode-resource:` URLs.

Thanks a lot in advance!

**Comment by tiagobento** [comment]
@deansheather Hi Dean! Any ideas from my last comment? Thx!

**Comment by deansheather** [comment]
Don't think there's a way to do this from Javascript running in the browser. VS Code sorts this out by changing the web request logic in electron, but we can't really do that since we're running in the browser.
