### ISSUE TITLE
How to install Synthwave '84 extension?

### ISSUE THREAD

**Issue by csskevin** [cdr/code-server#824]
Is there any way to install the Synthwave '84 Theme extension for code-server? I cannot find it in the extension catalog. 

This is the plugin: https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode

Any way to install this extension?

**Comment by csskevin** [comment]
Ok, I have installed it with manually. But why does the extension catalog doesn't show this plugin?

**Comment by deansheather** [comment]
As stated in our [README](https://github.com/cdr/code-server#extensions), we're unable to use Microsoft's marketplace due to licensing constraints, so we've made our own marketplace server which is based around open-source extensions. This extension is open-source, so we can definitely add it to our catalog.

**Comment by nhooyr** [comment]
See #1299
