### ISSUE TITLE
Allow use of systemd sockets

### ISSUE THREAD

**Issue by eimirae** [cdr/code-server#839]
I am using the already existing filesystem sockets to provide each user on my system to have their own code-server running.  I'm very happy with this, thanks.

I would like the ability for support for systemd sockets, where I can launch the systemd service when the socket is activated.

```
[Unit]
Description=<username>'s code-server socket
PartOf=<username>-code.service

[Socket]
ListenStream=/var/run/sockets/<username>

[Install]
WantedBy=sockets.target
```
From what I could tell, systemd is providing the socket as fd 3 to the application once it is started.  I tried to figure out a way to change the existing code to accomplish this, but I couldn't figure out what would need to be done.  Maybe something along these lines:

```
var http = require('http');
var systemdSocket = require('systemd-socket');

var server = http.createServer();
// set up handlers for error and request events
server.listen(systemdSocket() || 8080);
```

with httpolyglot, if it is capable of it.

**Comment by sr229** [comment]
I don't think its wise we add another feature that already has what Docker serves purpose as. Plus, adding the fact I don't think we should be dependent on one init system, we still have Upstart, OpenRC, etc. So I'm against supporting this since it only presents a complexity that users will be force to install something as part of it. `code-server` should be distro-agnostic as possible.

**Comment by deansheather** [comment]
This seems like a pretty niche feature. I'm not sure how well it will work, but could you try something like `code-server --socket /proc/self/fd/3` and see if it works?

**Comment by sr229** [comment]
We already have `--socket` so I think this will be closed now.
