### ISSUE TITLE
Keep getting "Lost connection ..."

### ISSUE THREAD

**Issue by dejunzhou** [cdr/code-server#872]
I'm seeing "Lost connection ..." messages in terminal window, once the connection lost, the contents are gone.  I have to rerun whatever was there in the terminal window again.  This is a bit annoying. Did anybody see the same?

From the server output, I can see below messages:

INFO  WebSocket opened / {"client":335,"ip":"127.0.0.1"}
INFO  WebSocket closed / {"client":335,"code":1005}
INFO  WebSocket closed / {"client":334,"code":1006}
INFO  WebSocket closed / {"client":333,"code":1005}
INFO  WebSocket opened / {"client":336,"ip":"127.0.0.1"}

I guess the websocket close was because of client network interruptions.  But don't we have ping/pong between client and server?

**Comment by deansheather** [comment]
Lost connection means your client is losing connection to the server. This is usually caused by a bad internet connection, so there's not much we can do about this. Try moving closer to the router, trying a mobile hotspot instead, or connecting to a different network.

Regarding the ping/pong, this should be handled by WebSocket's keep-alive mechanism.

**Comment by AlexanderJLiu** [comment]
@deansheather 
> this should be handled by WebSocket's keep-alive mechanism.

Has this mechanism been implemented? I found that if I do something else (like open other tabs in the same browser) less than 2 minutes and return back, the code-server will lose connection, I have to reconnect the code-server.

**Comment by deansheather** [comment]
@AlexanderJLiu I closed this issue back in the code-server v1 days, so I think your best bet would be to search for a newer issue or create a new one.
