### ISSUE TITLE
Feedback on 2.preview.1-vsc1.36.1

### ISSUE THREAD

**Issue by fbartels** [cdr/code-server#887]
Hi, just took the preview release for a short spin and wanted to provide some feedback.

1. the filename of the archive has changed
just a minor thing, but it meant that I had to adapt my update script (running the binary through systemd directly on my host).

The old filenames were code-serverversion-linux-**x64**.tar.gz
New filename is code-serverversion-linux-**x86_64**.tar.gz

2. parameter for version has changed
The current release uses the capital letter V, but the preview uses the small v to show version information.

3. server does not report unknown options
Related to 2. In my update script I print the version information, but running ´code-server -V´ did not complain about an unknown option, but instead started code-server. The current release does complain about unknown options.

4. file system provider for vscode-remote not available
In the preview I cannot browse my filesystem, but instead get the above error message. error persisted when downgrading (because of caching). had to clear my cache to get functionality with the old version back.

**Comment by sr229** [comment]
> 3. server does not report unknown options
Related to 2. In my update script I print the version information, but running ´code-server -V´ did not complain about an unknown option, but instead started code-server. The current release does complain about unknown options.

That sounds bad. @code-asher I don't think this is intended and I was able to replicate the issue as well.

**Comment by sr229** [comment]
@fbartels try out a [daily build](https://github.com/sr229/cdr-web-lkgr/releases) and see if any new changes fixes anything.

**Comment by fbartels** [comment]
Hi @sr229,

thanks for your feedback. Your build behaves in the same way to me as the preview above.

**Comment by code-asher** [comment]
Thanks for the feedback! :confetti_ball:

1. Ah, yeah, I thought this might cause some pain. :cactus: 
Basically now to detect the architecture I'm using `uname -m` and 
it returns `x86_64` instead of `x64` like Node's `os.arch()`. My 
thinking was that `x86_64` is _technically_ more correct so it 
would be wiser to use that.  <br>It's possible the changed file 
name is a good thing though because the default behavior for the 
new version is different. For example the default is http and no 
password now instead of https and a password and the flag for 
setting the authentication method to a password is different. So 
if you updated automatically you might suddenly find there is no 
password authentication or something like that.

2. This is because we just inherit the actual VS Code options now 
and VS Code uses a lowercase v. I think directly using VS Code's 
options will be better in the long run for us in terms of 
maintenance and compatibility.

3. I had the same thought but the new version just delegates the 
option handling to VS Code and apparently this is how it behaves. 
It seems this is on purpose: 
https://github.com/microsoft/vscode/pull/59806

4. We definitely need to have better caching behavior. I think 
using ETags would solve this?

**Comment by deansheather** [comment]
ETags are a good solution. You can use the etag package to generate an ETag based off of fstat metadata, without needing to hash the file.

**Comment by fbartels** [comment]
With https://github.com/cdr/code-server/releases/tag/2.preview.4-vsc1.37.0 I am not able to work again with code-server.

Just to sum up the original points:

1. yes, I do agree that the filename now better reflects the actual architecture. just mentioned it as this is a change to the current state.

2. ok, its of course a pity that the syntax has changed here, but using the same syntax as vscode if a good reason for this change. and since its a new major such changes are definitely acceptable.

3. then it seems the better place to complain about this is the "upstream" project :-D

4. directly works now after the upgrade to the latest preview.
